### ISSUE TITLE
key signature changes

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#105]
Key signature changes don't work at all if the piece starts in C major. 

![screen shot 2015-06-03 at 11 57 42 am](https://cloud.githubusercontent.com/assets/11529868/7964807/c861aeb8-09e7-11e5-9cc2-ef03bae42906.png)

However, if the piece has a key signature at the beginning already, when it changes throughout the piece, verovio just reiterates the original, rather than the new one:

![screen shot 2015-06-03 at 11 57 25 am](https://cloud.githubusercontent.com/assets/11529868/7964814/d4c8337a-09e7-11e5-8c12-1c55f634cbbc.png)

**Comment by lpugin** [comment]
The problem is actually that the initial key signature (key.sig) is defined in the staffDef and that the key changes in the scoreDef. This does not seem to be very consistent to me. If you put it either in the scoreDef at the beginning (also the key.mode), then it works fine. Alternatively, it can be in the staffDef an the beginning, but then the change also need to be in a staffDef (note than one limitation of Verovio for now is that staffDef needs to be within a scoreDef).

**Comment by lpugin** [comment]
I'll change this do documentation since it works but only if key.sig are placed consistently
