### ISSUE TITLE
Standard DPI

### ISSUE THREAD

**Issue by dominikmeixner** [rism-ch/verovio#1132]
Hey guys, I was wondering: 
what's the standard dpi when rendering? And can it be changed?
Because right now I'm manually adjusing the SVG size to fit onto the screen perfectly, which means I have to render multiple files, depending on the screen I'm using. When rendering e.g for an iPad with a resolution of "2388x1668" the SVG is obviously too big to fit.
Thanks for any answer!

**Comment by craigsapp** [comment]
The following pull request is related to the question and probably the answer you want:   https://github.com/rism-ch/verovio/pull/1023, which is set with the Javascript option `svgViewBox: 1`.  This should allow automatic scaling of the image to fit the region is needs to fill.

You can also set the width and scale (size) of the image with the `pageWidth: 2100` and `scale: 60` options.

There are no physical units for the pixels use in the units for pageWidth, but they are related to the pixels that the browser uses to describe the sizes of elements on the page.   If you have a known fixed with for the SVG image, then here is the calculation to get the desired width:

```
var targetWidth = 1500;
var vrvOptions = {};
vrvOptions.scale = 45;
vrvOptions.pageWidth = parseInt(targetWidth / (vrvOptions.scale/100.0));
```

Where `targetWidth` is the final size that you want, `vrvOptions.scale` is the scale option given to verovio when generating the SVG, and `vrvOptions.pageWidth` is the page-width option to give to verovio in order to get the desired target width for the image.



There is also an `mmOutput` option to set the units to millimeters rather than pixels, but I have never used that option, and I doubt that you should be using this method.
