### ISSUE TITLE
With Python bindings, pageHeight fails

### ISSUE THREAD

**Issue by mjwalter** [rism-ch/verovio#1135]
I'm using the Python bindings to try to set the page height, so that I can render pages of a particular size on a website (preferably one system per page).

I'm using something along the lines of `tk.setOption('pageHeight', '400')`. However, instead of altering the number of measures per page, it just crops the display. This means that when I go to page 2, several measures have been skipped. It also means that the cropping might take place in the middle of a system.

Using `tk.setOption('adjustPageHeight', 'true')` just makes the page always the default size.

Is this a known issue? Is there a possible fix?

**Comment by craigsapp** [comment]
> Using `tk.setOption('adjustPageHeight', 'true')` just makes the page always the default size.

`adjustPageHeight` is a vertical shrink wrap on the page: it removes any blank space at the bottom of the specified page height, potentially making the page height less than original if there is blank space at the bottom of the page.  This allows using a full page height for a short excerpt, with the result being an SVG which is not the full page height, but rather the height of the short example.

> I'm using something along the lines of `tk.setOption('pageHeight', '400')`. However, instead of altering the number of measures per page, it just crops the display. This means that when I go to page 2, several measures have been skipped. It also means that the cropping might take place in the middle of a system.

I do not think that this is a know issue, and I have never encountered it in the javascript and the command-line versions of verovio.   It could be something specific to the python interface.  One thing to try is using `400` rather than `'400'` to see if that makes any difference.

In Verovio Humdrum Viewer I have never noticed dropped measures.  Here is an example:

http://verovio.humdrum.org/?file=beethoven/sonata/sonata01-1.krn

When viewing in multi-page mode (VHV starts out in single-page mode, so click on the icon below the play button in the top right corner to activate multi-page mode), here is the first page with the given dimensions of the webpage automatically setting the page height and width parameters:

<img width="1247" alt="Screen Shot 2019-08-21 at 9 59 52 PM" src="https://user-images.githubusercontent.com/3487289/63480450-ed14a080-c45f-11e9-877c-7d7afc456bb3.png">

Clicking on the next page button (or pressing the right arrow key) moves to the second page which is :


<img width="1247" alt="Screen Shot 2019-08-21 at 10 00 00 PM" src="https://user-images.githubusercontent.com/3487289/63480513-23522000-c460-11e9-8619-d0f14adc6411.png">

The last measure on the first page is measure 29 and the first measure on the second page is measure 30.

If you want to see the Verovio options used to display, type `OPTIONS` on the javascript console:

<img width="1247" alt="Screen Shot 2019-08-21 at 10 08 36 PM" src="https://user-images.githubusercontent.com/3487289/63480538-35cc5980-c460-11e9-90f8-9d3bdafc85df.png">

**Comment by lpugin** [comment]
@mjwalter : could you post the file you use and the parameter you pass to the python toolkit?

**Comment by mjwalter** [comment]
@lpugin I'm sorry I missed this request! This happens for each file I have tried on the CRIM project website, including [CRIM_Model_0008](https://crimproject.org/mei/CRIM_Model_0008.mei) (link is to MEI download). These are the parameters I am using:

```
tk.loadData(mei)
tk.setOption('noHeader', 'true')
tk.setOption('noFooter', 'true')

# Calculate optimal size of score window based on number of voices
# Is not ideal, and should not be necessary if pageHeight and adjustPageHeight work as expected
# I have tried with and without adjustPageHeight, and also with a constant pageHeight including 60000
tk.setOption('pageHeight', str(150*len(data['voices']) + 110))
tk.setOption('adjustPageHeight', 'true')

tk.setOption('spacingSystem', '12')
tk.setOption('pageWidth', '2000')
tk.setScale(35)
data['svg'] = tk.renderToSVG(1)
```

**Comment by lpugin** [comment]
You need to call `tk.redoLayout()` after having changed options. Alternatively, you can load the data after having set all options. Let me know if this does trick.

**Comment by mjwalter** [comment]
Yes, loading the data after setting the options works! Thank you!
