### ISSUE TITLE
Only first movement of a MEI file is rendered

### ISSUE THREAD

**Issue by Noroxs** [rism-ch/verovio#1141]
I have a MEI file which contains multiple movements. But when I render the file I only get the SVGs for the first movement. 

Are movements supported by Verovio or should I perform XSLT to split the file in several peaces for each movement?

Example:
```
<mei>
    <music>
        <body>
            <mdiv type="symphony">
            <mdiv type="movement" n="1">
                <score> 
                    ...
                </score>
            </mdiv>
            <mdiv type="movement" n="2">
                <score> 
                    ...
                </score>
            </mdiv>
        <body>
    <music>
</mei>
```

**Comment by kepper** [comment]
Verovio is able to select an mdiv through XPath. The corresponding option is --mdiv-x-path-query (as documented [here](https://www.verovio.org/command-line.xhtml). Please note that the Javascript  version uses camelCase instead of dash-case (https://www.verovio.org/javascript.xhtml). If you go to the options section of the Verovio MEI Viewer, you can explore that option under the selector tab…

**Comment by Noroxs** [comment]
Thank you for the answer. 
I found the option but could you help me with the xpath query?
I loaded the file into the [Verovio MEI Viewer](https://www.verovio.org/mei-viewer.xhtml) and testet the following xpath query `//mdiv[@type='movement'][1]` which should select the second movement from my understanding. But unfortunately it doesn't change the content. 
Could you give me a hint how to do it correctly?

**Comment by kepper** [comment]
Your example above is a bit ambiguous, as you open an `<mdiv type="symphony">`, which seems to contain the two other `<mdiv>`s, but is never closed in the example. I assume you actually want to nest them, so that the closing tag for the symphony is missing at the end, and not before the movements. This is perfectly valid in MEI, but I don't know if Verovio is able to pick up nested mdivs (sorry, I haven't thought about that before…). The problem with your suggested XPath is that it already skips the symphony mdiv, and doesn't look into it anymore to get the first movement. Again, I don't know exactly how Verovio handles this situation internally (@lpugin?), but I would expect the following to work: `//mdiv[@type='symphony' or (@type = 'movement' and @n='1')]`. That way, the "outer mdiv" should pass, and the first inner should be selected…

**Comment by Noroxs** [comment]
Thank you again. I tried your xpath with the Verovio MEI Viewer but I still couldn't change to a different movement.

I created an extracted version of the original mei file with only 2 measures per movement. Maybe I'm using the Verovio MEI Viewer in a wrong way. I'm very thankful for your assistance!

[movementExample.txt](https://github.com/rism-ch/verovio/files/3609329/movementExample.txt)

**Comment by craigsapp** [comment]
> Ok, an XPath as simple as //mdiv[2] will do the trick, but (depending on the browser you use) you need to reload the file and hit the render button again to see the results…

That works for me:

(1) load file
(2) go to options -> element selectors -> mdiv xpath query and set to "//mdiv[3]"

<img width="914" alt="Screen Shot 2019-09-13 at 4 27 46 AM" src="https://user-images.githubusercontent.com/3487289/64860081-e69dc280-d5e0-11e9-8226-989f5245509b.png">

(3) Click on "Render" button under the step 1 "choose file" button:

<img width="200" alt="Screen Shot 2019-09-13 at 4 27 20 AM" src="https://user-images.githubusercontent.com/3487289/64860015-b524f700-d5e0-11e9-9fb0-962955c05e54.png">

Result:

<img width="336" alt="Screen Shot 2019-09-13 at 4 27 26 AM" src="https://user-images.githubusercontent.com/3487289/64860076-e3a2d200-d5e0-11e9-96d8-d7337b75ab6b.png">

-----

There seems to be a bug in the pugixml xpath command (or verovio's use of it).   There are four `mdiv` elements in this file, but index positions 1 and 4 are invalid input into verovio.  Position 1 would be expected to be invalid since that is the container for the symphony movements and does not contain any actual music (`<score>`):

```xml
      <mdiv type="symphony">
        <mdiv type="movement" n="1">
        </mdiv>
        <mdiv type="movement" n="2">
        </mdiv>
        <mdiv type="movement" n="3">
        </mdiv>
      </mdiv>
```

verovio complains about `//mdiv[1]`:

```
[Error] An <mdiv> with only one <score> descendant must be selected
```

which is to be expected since that is the `@type="symphony"`.

Using `//mdiv[2]` unexpectedly returns the second movement, and `//mdiv[3]` returns the third movement,  so using that xpath query method cannot access the first movement for some strange reason.

Using a different method to select only the mdiv that contain score elements works properly:

First movement: `'//mdiv[count(score)>0][1]'`

Second movement `//mdiv[count(score)>0][2]`

Third movement `//mdiv[count(score)>0][3]`

**Comment by kepper** [comment]
Well, in the `//mdiv[n]` XPath, the `n` is just a positional check, that is every mdiv that is the nth mdiv _relative to it's parent element_ will be selected. n=1 will fail because this results in two mdivs – the first with `@type="movement"` and the `@type="symphony"`. I would probably check the `@n`-attribute, so do something like `//mdiv[@n="2"]`. I just checked, and it works for me…

**Comment by craigsapp** [comment]
So `//mdiv[2]` would select two elements in the following example? (the second mdiv of each type="symphony"):

```
      <mdiv type="symphony">
        <mdiv type="movement" n="1">
        </mdiv>
        <mdiv type="movement" n="2">
        </mdiv>
        <mdiv type="movement" n="3">
        </mdiv>
      </mdiv>
      <mdiv type="symphony">
        <mdiv type="movement" n="1">
        </mdiv>
        <mdiv type="movement" n="2">
        </mdiv>
        <mdiv type="movement" n="3">
        </mdiv>
      </mdiv>
```

**Comment by kepper** [comment]
yes, that's how XPath works… with `//note[1]` you get every note that is the first note in its parent, so every first note in a layer, chord, beam, tuplet, you-name-it… If you want to have the first in the document, you can do `(//note)[1]`, where the brackets return a sequence of all notes (in document order), and out of that sequence you then pick the first…

**Comment by kepper** [comment]
and well, no, your example would return three mdivs – both with an `@n="2"`, plus the complete second symphony (given that the two root mdivs of your snippet don't have other preceding mdivs…)

**Comment by musicEnfanthen** [comment]
Just to summarize, in the specific case of @Noroxs , these expressions are equivalent:

First movement: 
`//mdiv[@n="1"]` = `//mdiv[@type='movement'][1]` = `//mdiv/mdiv[1]` =`(//mdiv)[2]`

Second movement: 
`//mdiv[@n="2"]` = `//mdiv[@type='movement'][2]` =  `//mdiv/mdiv[2]` = `(//mdiv)[3]`

etc.

- `//mdiv[@n="1"]` finds any mdiv with the specified number.

- `//mdiv[@type='movement'][1]` finds **every** first mdiv with specified type movement  (note that //mdiv[@type='movement'][4] will not work in @craigsapp 's case with two symphonies and 6 movements)

- `//mdiv/mdiv[1]` finds **every** first mdiv that is child of another mdiv

- `(//mdiv)[2]` finds the second instance of all mdivs in the document (only in this use case accidentally the first movement mdiv)

**Comment by craigsapp** [comment]
> and well, no, your example would return three mdivs – both with an @n="2", plus the complete second symphony (given that the two root mdivs of your snippet don't have other preceding mdivs…)

A ha 😱

**Comment by Noroxs** [comment]
Thank you all so much for your help and assist!
