### ISSUE TITLE
Rendering of two syllables on one note

### ISSUE THREAD

**Issue by ndubo** [rism-ch/verovio#1148]
In Italian, but I assume in other (Romance) languages as well, there may be two (sometimes even more) syllables on one note, one of them at the end of a word, the other one at the beginning (see third note; the full piece is found here: https://dme.mozarteum.at/movi/navigator/621/023/01/0013).

![image](https://user-images.githubusercontent.com/33256891/65349173-15202c80-dbe3-11e9-9903-b69749495166.png)

In the present case, the syllables in question are "-da" (which is wordpos="t") and "I-" (which is wordpos="i"). The correct coding therefore should be:

```
<note dur="8" oct="4" pname="f" tstamp="3" xml:id="note_7719">
	<verse xml:id="verse_7725">
		<syl con="s" wordpos="t" xml:id="syl_7731">da</syl>
		<syl con="d" wordpos="i" xml:id="syl_7732">I</syl>
	</verse>
</note>
```

(Alternatively, in the first syllable `con="t"` or `con="c"` is possible, but it should not be mandatory using these values).

The output of this code in Verovio is:

![image](https://user-images.githubusercontent.com/33256891/65349198-236e4880-dbe3-11e9-93c0-3f6f1b1a7176.png)

It works correctly only with the following coding, where the syllables are combined ("-da I-") and have the attribute `wordpos="m"`, which, however, is not correct:

```
<note dur="8" oct="4" pname="f" tstamp="3" xml:id="note_7719">
	<verse xml:id="verse_7725">
		<syl con="d" wordpos="m" xml:id="syl_7731">da I</syl>
	</verse>
</note>
```
Verovio should allow two syllables on one note, each of them with their unique `wordpos `and appropriate `con`.

**Comment by craigsapp** [comment]
Lyrics were implemented relatively early in verovio's history, so this aspect has not been fully addressed, and now might be a good time to review it.

The current behavior of verovio is to place all characters to be displayed under one note into a single `<syl>`:

```xml
<verse n="1">
   <syl con="d" wordpos="m">da I</syl>
</verse>
```

The `@wordpos` is set to `m` because there are dashes on either side of the "syllable", and `@con` is set to `d` because there is a dash after the "syllable".  There can be interpretation on whether or not this is correct: technically this can be viewed as a single syllable for singing, but for text extraction it would better be encoded as two separate syllables.

Here is the current verovio rendering:

<img width="483" alt="Screen Shot 2019-09-20 at 1 13 00 PM" src="https://user-images.githubusercontent.com/3487289/65356165-9dcda700-dba8-11e9-905b-211f0b497884.png">

Full MEI excerpt:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2019-09-20T13:10:51" version="2.2.0-dev-b5cea99">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workList>
            <work>
                <title />
            </work>
        </workList>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000318231272">
                <score xml:id="score-0000000444204731">
                    <scoreDef xml:id="scoredef-0000000961365691">
                        <staffGrp xml:id="staffgrp-0000000186156615">
                            <staffDef xml:id="staffdef-0000000800450532" n="1" lines="5">
                                <clef xml:id="clef-0000000202173802" shape="G" line="2" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-L1F1">
                        <measure xml:id="measure-L1" n="0">
                            <staff xml:id="staff-0000001248594570" n="1">
                                <layer xml:id="layer-L1F1N1" n="1">
                                    <note xml:id="note-L3F1" dur="8" oct="4" pname="a" accid.ges="n">
                                        <verse xml:id="verse-L3F2" n="1">
                                            <syl xml:id="syl-L3F2" con="d" wordpos="i">di</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-L4F1" dur="8" oct="5" pname="c" accid.ges="n">
                                        <verse xml:id="verse-L4F2" n="1">
                                            <syl xml:id="syl-L4F2" con="d" wordpos="m">scen</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-L5F1" dur="8" oct="4" pname="f" accid.ges="n">
                                        <verse xml:id="verse-L5F2" n="1">
                                            <syl xml:id="syl-L5F2" con="d" wordpos="m">da I</syl>
                                        </verse>
                                    </note>
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L6">
                            <staff xml:id="staff-L6F1N1" n="1">
                                <layer xml:id="layer-L6F1N1" n="1">
                                    <beam xml:id="beam-L7F1-L9F1">
                                        <note xml:id="note-L7F1" dots="1" dur="8" oct="4" pname="b" accid.ges="n">
                                            <verse xml:id="verse-L7F2" n="1">
                                                <syl xml:id="syl-L7F2" con="d" wordpos="m">me</syl>
                                            </verse>
                                        </note>
                                        <note xml:id="note-L8F1" dur="32" oct="5" pname="c" accid.ges="n" />
                                        <note xml:id="note-L9F1" dur="32" oct="5" pname="d" accid.ges="n" />
                                    </beam>
                                    <note xml:id="note-L10F1" dur="8" oct="5" pname="c" accid.ges="n">
                                        <verse xml:id="verse-L10F2" n="1">
                                            <syl xml:id="syl-L10F2" wordpos="t">ne</syl>
                                        </verse>
                                    </note>
                                </layer>
                            </staff>
                            <slur xml:id="slur-L7F1-L9F1" staff="1" startid="#note-L7F1" endid="#note-L9F1" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

----------------------

Related to the discussion is that there is typically an elision mark instead of a space between such elided syllables.  This is currently implemented in verovio with a hack by using an underscore character rather than a space:

```xml
<verse xml:id="verse-L5F2" n="1">
   <syl xml:id="syl-L5F2" con="d" wordpos="m">da_I</syl>
</verse>
```

which renders as:

<img width="462" alt="Screen Shot 2019-09-20 at 1 10 32 PM" src="https://user-images.githubusercontent.com/3487289/65356459-6a3f4c80-dba9-11e9-83e3-8de48da9fc4b.png">

I use this encoding method in the Tasso in Music Project website's scores, such as:
http://www.tassomusic.org/work/?id=Trm0047m
E.g., end of measure 5 in the canto part.  There is a link to the MEI data underneath the score.

To display an elision character (of this style), `@con="b"` should be used:
     https://music-encoding.org/guidelines/v4/elements/syl.html

So displaying the example syllable using an elision character should more properly be encoded as:

```xml
<verse n="1">
   <syl  wordpos="t" con="b" >da</syl>
   <syl wordpos="i" con="d" >I</syl>
</verse>
```

--------------------

In terms of implementation, I will remind whomever implements an upgrade 😉 that at system breaks, I would still want to see a prefix hyphen in such cases (in this case due to the first syl having `@wordpos="t"`, and in the original encoding because the syl cluster had `@wordpos="m"`.  An example from the same Tasso score:

<img width="957" alt="Screen Shot 2019-09-20 at 1 33 21 PM" src="https://user-images.githubusercontent.com/3487289/65358245-efc4fb80-dbad-11e9-8c9e-6ed98b977c26.png">

(in the Canto part on the last syllable of the word Aventò)


In terms of styling, it would be useful to have an option for how to connect words within a single `<verse>`.  In other words to make it easy to switch between using an elision (breve or other style) and space for the separate syllables in a single `<verse>`.  This could be done as an option to verovio, such as `--verse-word-connector "b"` to use the breve elision as a default, or `--verse-word-connector="s"` to use a space.  Probably this would not overwrite any explicit `@con`, though.

**Comment by rettinghaus** [comment]
The hack was originally implemented to address a sibmei issue, which has been fixed here:  https://github.com/music-encoding/sibmei/commit/16f8c8685fd4710241ad29f161b4b7fe20e083e4
So basically, there is no need to keep this behaviour any longer ;-)

**Comment by ndubo** [comment]
> There can be interpretation on whether or not this is correct: technically this can be viewed as a single syllable for singing, but for text extraction it would better be encoded as two separate .<

In my opinion, there is only limited room for interpretation. Two elided vowels – or maybe more correctly ‘syllables that are subject to synalepha’, since nothing gets elided, the vowels are practically ‘melted’ into one – in a wordend / wordstart position are logically ‘two vowels in a wordend / wordstart position’. Only in a ‘gestural’ context, they may be called one syllable in a wordpos-m position. But this should not be the norm and it should not be our goal.
Yes, ‘text extraction’, in a larger sense. If, for example, I want to connect the encoded lyrics to an independent edition/encoding of the poetry, maybe in TEI, I need to be able to correctly identify the syllables.

> there is typically an elision mark instead of a space between such elided syllables.

This is just a matter of choice. I consider the mark a crutch and I would not add it unless it is already in my source or if I prepare an edition for a specific readership. In short, the elision mark should not be the norm.

**Comment by lpugin** [comment]
Implemented
