### ISSUE TITLE
Option to hide measure numbers

### ISSUE THREAD

**Issue by earboxer** [rism-ch/verovio#1153]
We have "No header" and "No footer" options. It would also be nice to have a "No measure number" option.

**Comment by craigsapp** [comment]
That would be useful to have.  There is an option called `--measure-number` which is not implemented to do anything yet (that I can tell).  The options are `system` which would number the first measure of each system (this is the default behavior), and `interval` which would number every fixed number of measures, such as every 5 or 10.  But there is no way current to set the interval?  

A better system would be to allow an integer to `--measure-number`.  When the option is not used, the default system numbering would be used, when the integer is 0, then no measure numbers would be displayed, and a positive integer would be the measure interval to display the numbers at.

A related issue ishttps://github.com/rism-ch/verovio/issues/909, where examples of forcing measure numbers to display are given.

Another solution is given in issue https://github.com/rism-ch/verovio/issues/374, where you remove the measure number via XSLT before sending to verovio.

**Comment by rettinghaus** [comment]
You could even use `g.mNum {display:none}` in css.

**Comment by craigsapp** [comment]
That is a good way, although there will be cases where notational elements are moved to avoid a measure number that is now invisible, so the notation may occasionally look strange.

**Comment by earboxer** [comment]
> A better method would be to allow an integer to --measure-number. When the option is not used, the default system numbering would be used, when the integer is 0, then no measure numbers would be displayed, and a positive integer would be the measure interval to display the numbers at.

I'm not sure any values besides 0, 1, and null would be helpful.

An image search for sheet music shows two major practices

* showing measure numbers at the beginning of each system except the first (i.e. verovio's default numbering)
* showing no numbering

If more complicated numbering is desired, perhaps that would be something that should come from the MEI files.

Does MEI (or MusicXML) have anything related to hiding/showing measure numbers?

**Comment by craigsapp** [comment]
> I'm not sure any values besides 0, 1, and null would be helpful.

A common third style is to display the measure number at every 10th measure, regardless of its position on the system.  Occasionally every 5th barline is numbered.  This system is useful for orchestral parts when rehearsal marks are not used since every part will have different system breaks.

Here is an example of this numbering style:

http://conquest.imslp.info/files/imglnks/usimg/7/7e/IMSLP04090-Beethoven_-_Piano_Sonatas_Lamond_-_27.pdf

<img width="845" alt="Screen Shot 2019-10-09 at 8 20 58 AM" src="https://user-images.githubusercontent.com/3487289/66495119-9a259580-ea6d-11e9-837a-790576a67e3d.png">


A measure numbering interval of "1" would not be used in music to be performed, but may be useful for analytic purposes.

**Comment by craigsapp** [comment]
Another tangential issue (beyond the scope of this issue but good to think about) related to measure number styles is that there are cases where there are two measure numbers for each measure.  The first one is the measure number in the entire work, and the second number, usually in parentheses, is the measure number in the movement.  This is more common in opera and ballet scores.   

Example:  `640 (30)`

which would mean that this measure is number 640 in the entire work, but measure 30 of the current movement.

Is this sort of dual measure numbering representable currently in MEI?

**Comment by earboxer** [comment]
Reminds me of #1111.

**Comment by earboxer** [comment]
@craigsapp 

The answer is yes

You just need

```xml
<measure>
  <mNum>640 (30)</mNum>
```

in your MEI file.

**Comment by earboxer** [comment]
Closing as a duplicate of #374 

The solutions are data-side. You can either
```diff
-<measure n="10">
+<measure>
```

```diff
 <measure n="10">
+  <mNum></mNum>
```

If your source files are musicXML files, you can do
```diff
-<measure number="10">
+<measure>
```

Note that `<measure number="10" implicit="yes">` from musicXML doesn't work to hide the measure numbers.

From the MusicXML spec:

> The implicit attribute is set to "yes" for measures where the measure number should never appear, such as pickup measures and the last half of mid-measure repeats. The value is "no" if not specified.

**Comment by craigsapp** [comment]
> but you risk making your musicxml file invalid

Yes, removing `measure@number` will make the MusicXML file invalid against validation, since it is a required attribute.  Not a problem if you remove the attribute as a temporary process when converting to MEI, but you should not save the MusicXML data without `measure@number`.

http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML.htm%3FTocPath%3DMusicXML%2520Reference%7CScore%2520Schema%2520(XSD)%7CElements%7C_____0

![Screen Shot 2019-10-09 at 12 33 29 PM](https://user-images.githubusercontent.com/3487289/66513838-d0284100-ea90-11e9-92a5-98c6c6025338.png)

So if you remove `@number` from the measure in MusicXML data, it is technically no longer valid MusicXML.

The primary purpose of`measure@number` is to allow transformation between part-wise and score-wise versions of MusicXML (not to provide measure numbers for the score).  The `@number` elements are used to collect the same measure content from each part to assemble the score-wise view.  MEI is a purely score-wise organization (from MusicXML's viewpoint), and the `<measure@n>` equivalent attribute is optional:

https://music-encoding.org/guidelines/v4/elements/measure.html

![Screen Shot 2019-10-09 at 12 38 51 PM](https://user-images.githubusercontent.com/3487289/66514234-91df5180-ea91-11e9-853d-b0476e539598.png)

I find that the `measure@number` values in MusicXML files are not useful when dealing with pickup measures, as the pickup measure is (or was) labeled as `@number="1"`.  Originally the number attribute was limited to positive integers in MusicXML, so pickup measures could not be labeled measure "0". But now it is possible to label a pickup measures as number "0" since the number attribute is allowed to be text.  When I convert from MusicXML, I usually automatically renumber to handle pickup measures and split measure numbers better than they are handled in the encoding.

**Comment by lpugin** [comment]
Sorry, but I am a bit lost in this discussion and the PRs. I do not think having empty `<mNum>` is a good way to avoid the display of measure numbers. 

The current default behavior based on `measure@n` and not displaying the measure number for the first system works for most cases and should be kept. Also, Verovio takes into account existing `<mNum>`, which should also be kept. 

What I think we need is a few more options to control the display, as initially suggested. The `--measure-number` option was put there to do so, but it was indeed never implemented. What I am suggesting to have is:
* --mnum-interval (default is 0, meaning every system, and other values for number in the system)
* --mnum-hidden (default is false, true means do not show anything)
* --mnum-show-first (default is false, true means force display for the first system)

I am also thinking of implementing an auto increment approach base on the `<mNum>` in the first measure. This can be handy with double numbering. We could then do:
```xml
<measure n="1">
	<app>
		<rdg type="mvt">
			<mNum>1</mNum>
		</rdg>
		<rdg type="work">
			<mNum>234</mNum>
		</rdg>
	</app>
</measure>
```
Without having to add it to every single measure, but then still easily switch from one numbering to another. Of course, this would work only with integer values.

**Comment by rettinghaus** [comment]
Thanks @lpugin. But I suggest to (implement and) use `@mnum.visible` on `<scoreDef>` and have that behavior overwritten with a `--mnum-visible` option instead of `--mnum-hidden`.

**Comment by lpugin** [comment]
> Thanks @lpugin. But I suggest to (implement and) use `@mnum.visible` on `<scoreDef>` and have that behavior overwritten with a `--mnum-visible` option instead of `--mnum-hidden`.

Well spotted! Then I would simply forget that option. Having options duplicating MEI features is not a good practice and we should avoid it.

**Comment by rettinghaus** [comment]
Yeah, but didn't we already? 
`--spacing-staff=SP         Specify the spacing above each staff (in MEI vu)`
`--spacing-system=SP        Specify the spacing above each system (in MEI vu)`

`@spacing.staff(optional)Specifies the minimum amount of space between adjacent staves in the same system; measured from the bottom line of the staff above to the top line of the staff below. Value conforms to data.MEASUREMENTREL.`
`@spacing.system(optional)Describes the space between adjacent systems; a pair of space-separated values (minimum and maximum, respectively) provides a range between which a rendering system-supplied value may fall, while a single value indicates a fixed amount of space; that is, the minimum and maximum values are equal. One or two values from data.MEASUREMENTREL, separated by a space.`

**Comment by lpugin** [comment]
> Yeah, but didn't we already?

Did I say we do not? We do, but it is not a reason to have some more. I was simply a bad idea, and we should stop.

**Comment by earboxer** [comment]
So we want to

- [ ] implement `<scoreDef mnum.visible="false">` (and don't implement any options to overwrite this)

Then to hide measure numbers, we just make our MEI score like

```xml
<mdiv>
  <score>
    <scoreDef mnum.visible="false"></scoreDef>
    <section>
      <measure n="0"></measure>
      <measure n="1"></measure>
      <measure n="2"></measure>
```

Is there a way we could get this from a musicXML file?

the `print` element has a `measure-numbering` element, I think `print` can only be used in measures.

**Comment by rettinghaus** [comment]
I propose to check the first `print` element for a value of `none` on `measure-numbering`. 
https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-measure-numbering-value.htm

**Comment by lpugin** [comment]
> But I suggest to (implement and) use `@mnum.visible` on `<scoreDef>`

It is actually already implemented.
