### ISSUE TITLE
Allow shortest duration to be 1024 (SMuFL shortest flag)

### ISSUE THREAD

**Issue by napulen** [rism-ch/verovio#1172]
According to a discussion at the `mei workshop` in Nashville, the maximum duration supported by `MEI 4.0.1` is `dur="2048"`, however, Verovio renders correctly notes up to `dur="256"`

**Comment by rettinghaus** [comment]
Verovio != MEI

**Comment by napulen** [comment]
However, `verovio_input_data = ('MEI',)`

I believe Laurent mentioned complying with `dur=1024` because that is the limit defined by `SMuFL`

**Comment by rettinghaus** [comment]
I'm not against supporting this, but some people do think Verovio *is* MEI. So that was just a reminder. :-)

**Comment by napulen** [comment]
Understood :-).

**Comment by valeriyvan** [comment]
Anyone aware of a document where all limitations of Verovio are listed?

**Comment by lpugin** [comment]
There is no really such thing because it would be a huge subset of MEI. However, Verovio raises a warning when a value is not supported. When loading `note@dur="512"` you will see `[Warning] Unknown dur '512'`.

There were some attempts to build an MEI schema reflecting the status of Verovio but it never succeeded. The best overview is provided by the doxygen documentation http://rism-ch.org/verovio-doxygen/html/hierarchy.html (version number needs to be updated but the documentation is accurate)

**Comment by lpugin** [comment]
Fixed
