### ISSUE TITLE
Document possible issues with text fonts on different OS / browsers

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1175]

**Comment by craigsapp** [comment]
Do you have an example?  They are centered for me:

http://www.tassomusic.org/work/?id=Trm0047m

<img width="316" alt="Screen Shot 2019-10-29 at 5 40 08 AM" src="https://user-images.githubusercontent.com/3487289/67767721-5a1f5600-fa0e-11e9-8510-ff6f0c110a96.png">

**Comment by rettinghaus** [comment]
Which version are you using? 
E. g. look at https://www.verovio.org/features.xhtml?id=lyrics
Also spacing is poor and underscores start to early.

**Comment by lpugin** [comment]
It looks like nothing has change since version 2.0

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/689412/67771400-3831cd80-fa26-11e9-8a35-46f671252bb6.png">

**Comment by craigsapp** [comment]
The example you give is not encoded in a way that allows for centered dashing:

<img width="454" alt="Screen Shot 2019-10-29 at 6 37 16 AM" src="https://user-images.githubusercontent.com/3487289/67771848-4b3ca180-fa16-11e9-83f1-a9c1c0934622.png">

In other words the dash is in the text of the syllable rather than as an attribute.

**Comment by rettinghaus** [comment]
@craigsapp perhaps you could scroll down a bit?

**Comment by craigsapp** [comment]
You are the one who usually complains about vague issue posts 😛 

They all look good to me (other than font metrics are not used for different fonts in the styling examples).  But I see a bug in the second example:

<img width="599" alt="Screen Shot 2019-10-29 at 7 51 07 AM" src="https://user-images.githubusercontent.com/3487289/67778541-9196fe00-fa20-11e9-9437-31ae91c88ed2.png">

The first dash in each verse is not centered, but the secondary dashes on the lines are correct.  The problem is due to the space in the syllable:

```xml
<syl wordpos="i" con="d">1. Je</syl>
```
If the space is removed, the dashes are placed correctly:

<img width="370" alt="Screen Shot 2019-10-29 at 7 54 51 AM" src="https://user-images.githubusercontent.com/3487289/67778888-1c77f880-fa21-11e9-929d-383c58beee8d.png">

Here is an exaggeration to highlight the problem:

<img width="482" alt="Screen Shot 2019-10-29 at 7 55 05 AM" src="https://user-images.githubusercontent.com/3487289/67778915-26016080-fa21-11e9-91da-3ffcf0921092.png">

```xml
<syl wordpos="i" con="d">X         Je</syl>
```

There are likely two problems:

(1) The font metrics for the space in the middle of the syllable is incorrectly too large.  Note that if this is fixed, do not mess up the solution for issue https://github.com/rism-ch/verovio/issues/507.
(2) The length of the syllable is calculated before extra whitespace is removed.  Notice that there are a lot of extra spaces between the `X` and `Je`  sub-syllables, and these extra spaces control placement of the dash after the syllable.  These extra spaces should be removed before calculating the width of the syllable (or alternatively, treat the spaces as `&nbsp;` and preserve them).

If you look at the examples in issue https://github.com/rism-ch/verovio/issues/1148, the problem is also seen there (the dash after `da I`).

-----------------------------------------------------

Related to this, I think there is a more proper way of adding verse number prefixes to the syllables in MEI.  And is this implemented in verovio?  A secondary problem with the second example on the page is that the `1.` at the start of the verse should be displayed *before* the note, not coincident with the note.  The current encoding should not be expected to deal with that since the number is treated as part of the syllable.

**Comment by craigsapp** [comment]
>  underscores start to early

I still do not see this one.

<img width="219" alt="Screen Shot 2019-10-29 at 8 09 39 AM" src="https://user-images.githubusercontent.com/3487289/67780291-226ed900-fa23-11e9-9460-be38485e65e7.png">

**Comment by lpugin** [comment]
Having spaces in a syllable does not make much sense to me. What should actually be changed is the numbering of the verses. In that case, it seems that this issue duplicates with #913, doesn't it?

**Comment by craigsapp** [comment]
> Having spaces in a syllable does not make much sense to me. What should actually be changed is the numbering of the verses. In that case, it seems that this issue duplicates with #913, doesn't it?

Yes, that is what I was thinking of.  However, how are you going to deal with issue #1148? Currently the only way to encode this is with a single syllable with a space in the middle.  That issue suggests splitting the two syllables into separate `<syl>` containers, so the space will be added automatically by verovio (but there still would be a spacing bug due to the constructed space).

**Comment by rettinghaus** [comment]
I figured out what the problem actually is. It's only Firefox on Linux (Ubuntu), that mashes the layout. And it's not only the js toolkit. Rendered with command line version the resulting file looks like this in Chrome: 
![Bildschirmfoto von 2019-10-29 17-08-10](https://user-images.githubusercontent.com/7693447/67786995-1a895600-fa70-11e9-9a23-55e992c35ce8.png)
And this is what Firefox shows:
![Bildschirmfoto von 2019-10-29 17-09-54](https://user-images.githubusercontent.com/7693447/67786997-1a895600-fa70-11e9-9287-a6a26fe664ad.png)
It uses "DejaVu Serif" as default font, which is larger than the one used in Chrome. Firefox on Windows works fine, so long Windows has "Times New Roman" set as default serif font. 
So it's not really a Verovio issue, but maybe should be noted somewhere?

**Comment by craigsapp** [comment]
> So it's not really a Verovio issue, but maybe should be noted somewhere?

Yes, that is not directly controllable by verovio: a specific font metric is needed in order to set words in the music (lyrics as well as text directions and such).  When the font is changed (or at least different from the metrics), the musical spacing in the SVG image cannot automatically change since the SVG image and software to manipulate it are not aware of the musical content.

It might be useful to note at the lyrics styling example on the discussed webpage.

When I view the page in Firefox on MacOS, the text spacing is good:

<img width="644" alt="Screen Shot 2019-10-29 at 9 52 02 AM" src="https://user-images.githubusercontent.com/3487289/67789776-c6f81780-fa31-11e9-9fba-84a95fd1ce36.png">

And the text variations are closer than Chrome on MacOS:

<img width="360" alt="Screen Shot 2019-10-29 at 10 42 55 AM" src="https://user-images.githubusercontent.com/3487289/67793897-e9d9fa00-fa38-11e9-8396-2817e48efc10.png">
