### ISSUE TITLE
System dividers options

### ISSUE THREAD

**Issue by Noroxs** [rism-ch/verovio#1188]
Is it possible to add `system dividers` options to Verovio?

Possible options could be:
- Position: leading (left), center, trailing (right)
Instead of drawing the system dividers always at the left side of the SVG this option would modify the system divider polygons so that the element is positioned to the left, center or right.
- Thickness: thin, medium, bold
Change the thickness of the lines for the system dividers.
- Color: Define color for the system divider element
  - Unique IDs: Instead of allowing Verovio to define the color for the system dividers it would also be possible to add an unique identifier to the system divider element. This identifier could be used for changing the `fill` attribute in the SVG via XSLT or other techniques.

With system dividers I mean the sign between systems in the SVG file. Example:
<img width="38" alt="Screenshot 2019-11-17 at 13 23 36" src="https://user-images.githubusercontent.com/1566243/69007621-7c86fe00-0940-11ea-97ae-b92844ad5f14.png">

**EDIT:** Changed to correct term `system dividers` instead of `line breaks`

**Comment by rettinghaus** [comment]
They are called `system dividers` or `system separators`.

**Comment by lpugin** [comment]
There is now a system-divider option that takes "none", "left" (default) and "left-right".  They are now wrapped in a distinct SVG g@class "systemDivider" element, which makes it possible to control their color via CSS. Ids in not really applicable since system dividers do not correspond to an MEI element.

Placement: center was not clear to me as a desired output. Feel free to make a PR with additional options now that the basic handling is there.

Styling (thickness): this is beyond what is typically controlled elsewhere via Verovio options. We can add this once we have a styling mechanism in place.
