### ISSUE TITLE
Playing the MIDI output in iOS Question

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1249]
Thanks for your help

1.Goal: when the midi file exported from the staff is played, the corresponding notes will change color, similar to https://www.verovio.org/tutorial.xhtml?id=topic09

2.Through the study of the tutorial, I know that this process is required
  (1)Get the playing time of each note
 (2)Substitute vrvTime into the getElementsAtTime method
 (3)Cycle nodesid to make notes color

3.Since there is no midi player, I substituted a fake time parameter, such as vrvTime = 250, and then substituted that time into the getElementsAtTime method, but it did not return my parameters.

4.With your guidance, I can export something similar by vrvToolkit.renderToTimemap () method
<img width="307" alt="屏幕快照 2020-01-06 下午3 29 19" src="https://user-images.githubusercontent.com/19338570/71803975-295a3d80-309d-11ea-92fe-8a0bbf0ff444.png">

5.Question: I don't know how the vrvToolkit.renderToTimemap () method is related to getElementsAtTime (), or is there any other way to achieve my goal?

Thank you in advance for your help!

**Comment by lpugin** [comment]
> 5.Question: I don't know how the vrvToolkit.renderToTimemap () method is related to getElementsAtTime (), or is there any other way to achieve my goal?

They were related by the fact that you had to call `vrvToolkit.renderToTimemap()` before calling `getElementsAtTime()` in order to have values. It is now no longer be necessary since this was changed (see 10d549c738f6ecec9321af52f4ab9dd83c157d34), calling `getElementsAtTime()` should always return a value.

(in the future, a `Toolkit::RedoTimemap()` method will probably be useful in order to be able to force for the timemap to be re-generated)
