### ISSUE TITLE
Playing the MIDI output in iOS Question (2)

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1254]
@lpugin    By modifying 10d549c in the local project, but there are still problems

1.Because there is no midi player, I try to bring the time parameter            
 obtained by vrvToolkit.renderToTimemap () into the getElementsAtTime 
 method

2.code show as below
       
     ```
           let vrvTime = 1250
           let elementsattime = vrvToolkit.getElementsAtTime(Int32(vrvTime))
            
           Calling C ++ code
           -(NSString *)getElementsAtTime:(int)time{
           std::string elements = self.toolkit->GetElementsAtTime(time);
           return [NSString stringWithCString:elements.c_str()  
           encoding:NSUTF8StringEncoding];                   
           } 
    ```

3.Still nothing,And through the interruption point, I found that I did not enter the m_doc.CalculateMidiTimemap (); method

**Comment by lpugin** [comment]
I am sorry, but I do not understand the issue. The fact that there is no player does not seem relevant to me. I the online MEI viewer, in the console, I can do:
```js
vrvToolkit.getElementsAtTime(1200)
```
and it returns:
```js
{
  "notes": [
    "d414233e89",
    "d414233e315"
  ],
  "page": 1
}
```
This is the expected behavior. That is, it returns a list of sounding notes at a particular time, but it does not play anything.

(If you want to play the output, you should look for a way in iOS to play the MIDI file obtain through `.renderToMIDI()` and then you can use this method or the timemap to synchronize it with the score.)

**Comment by yangyangnote** [comment]
@lpugin Sorry, my description is not very accurate, and my English is not good. 
The problem is simple, it has nothing to do with the midi player

Is what I now pass the 

`vrvToolkit.getElementsAtTime (1200) `

Cannot get

```
{
  "notes": [
    "d414233e89",
    "d414233e315"
  ],
  "page": 1
}
```

Similar data
Similar writing, I call other methods, and it is easy to get the data.
