### ISSUE TITLE
Unsupported value 'x' for data.ACCIDENTAL.GESTURAL

### ISSUE THREAD

**Issue by davidnalesnik** [rism-ch/verovio#1291]
Either I am missing something, or it does not seem to be possible to create a hidden double-sharp.

**Comment by rettinghaus** [comment]
You missed to have a look at the guidelines:
https://music-encoding.org/guidelines/v4/data-types/data.accidental.gestural.html

**Comment by davidnalesnik** [comment]
Ah, thank you!  (Forgive me, I am a newcomer, and not yet adept at finding Verovio/MEI information.)

**Comment by davidnalesnik** [comment]
I see here (https://music-encoding.org/guidelines/v4/data-types/data.accidental.written.html) that written double-sharps can be either the usual "x" or a double-sharp written as 2 sharps--"ss".  Yet, only "ss" is a viable gestural accidental.  Why not accept all values in both categories?  The current situation leads to unnecessary complexity, IMO.

**Comment by kepper** [comment]
In source material, both “writing styles” can be found. If one wants to preserve the visual rendition, both values are necessary. However, there is no difference in how they sound, so having two different values representing this perspective (we frequently call these things different domains of music) would actually be inadequate. Yes, that’s not very intuitive, but it’s faithful to music notation, which isn’t very consistent and intuitive in itself ;-) 

To make a long story short: your thoughts are absolutely ok, and we all went through this. We’re glad to have you here, so don’t bother to ask – there are no dumb questions when it comes to MEI ;-)

**Comment by craigsapp** [comment]
Think of `@accid.ges` as a number (which would be less confusing, since it would then be more different than `@accid`):

number| accid.ges | meaning
---------|--------|--------
1|s |Sharp.
-2|f |Flat.
2|ss| Double sharp.
-2|ff| Double flat.
0|n| Natural.
1.5|su| Three quarter-tones sharp.
0.5|sd| Quarter-tone sharp.
-0.5|fu |Quarter-tone flat.
-1.5|fd | Three quarter-tones flat.

Other proposed accidental states for higher numbers:

https://github.com/music-encoding/music-encoding/issues/639

**Comment by lpugin** [comment]
I am leaving this to be discussed on music-encoding if necessary.
