### ISSUE TITLE
[Warning] Justification is highly compressed, overlapping content

### ISSUE THREAD

**Issue by palgranum** [rism-ch/verovio#1301]
See rendered page 4, lyrics are overlapping and it seems like Verovio is laying out two bars when there is only space to fit one bar.
 
![page4](https://user-images.githubusercontent.com/57617454/74352440-c9039d80-4db8-11ea-86df-68dd562a5744.png)

I also enclose screenshot of previous/next page where only one bar is laid out and overlapping does not occur, so I am curious why this happens on page 4 in this file.

![page3](https://user-images.githubusercontent.com/57617454/74352438-c86b0700-4db8-11ea-8812-966b36d2a4ad.png)

![page5](https://user-images.githubusercontent.com/57617454/74352435-c6a14380-4db8-11ea-87f9-26ccf522354d.png)

Steps to reproduce this example (using latest 2.5 build of Verovio):
Verovio VaPensiero.mei -r data -p 3 --page-width 1200 --page-height 1800 -o page3.svg
Verovio VaPensiero.mei -r data -p 4 --page-width 1200 --page-height 1800 -o page4.svg
Verovio VaPensiero.mei -r data -p 5 --page-width 1200 --page-height 1800 -o page5.svg

When executing page 4 command, Verovio give these warnings:
[Warning] Justification is highly compressed (ratio smaller than 0.8: 0.545978)
[Warning] 	System full width: 11000
[Warning] 	Non-justifiable width: 2474
[Warning] 	Drawing justifiable width: 15616
[Debug] Hyphen space under the limit
[Debug] Hyphen space under the limit
.....

Mei file and svgs are attached.

[VaPensiero.zip](https://github.com/rism-ch/verovio/files/4193266/VaPensiero.zip)

**Comment by lpugin** [comment]
This is a known issue. The problem comes from the "cantabile : tutti sotto voce" indication that overlaps two measures and prevent a system break to happen here. Unfortunately, there is no easy way to fix this because splitting text is not easy - which is why system breaks are precluded. Justification will be improved at some point, but improving the justification will not guarantee that it can work in any case if the content is just too dense.  The best so to at this stage if you want to avoid this is to split directive into shorter ones that to do not overlap several measures, or to use fixed (encoded) layout and an appropriate page width.
