### ISSUE TITLE
build option for editor toolkit

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1306]
The editor toolkit is activated in builds with `NO_HUMDRUM_SUPPORT`. Shouldn't be there an extra option to turn this on or off? AFAICS it is not necessary for standard builds, is it? 

Anyhow this should be mentioned in the wiki.

**Comment by lpugin** [comment]
The editor toolkit is not related to the humdrum support. In theory, it would make sense to have distinct builds turning on / off specific features. However, we need to find a balance because there is a the risk to end up with too many build options. A trade-off was found with the NO_HUMDRUM_SUPPORT because the humdrum part is large and increases the compilation time and executable size significantly. I do not think this is the case with the editor toolkit and we should leave it like this - unless it causes you concrete problems?

What would you like to see mentioned in the wiki?

**Comment by rettinghaus** [comment]
1. There *is* a editor toolkit. 
2. Builds contain either this or that.

**Comment by lpugin** [comment]
I looked at the wiki and it seems clear enough (basically explaining the humdrum is / can be turned off, and same with PAE - this used to be desirable when regex was causing compilation issues on some platforms). The editor is still very experimental. We can document it better in due course. Closing for now.
