### ISSUE TITLE
Changing the style of a note element

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#132]
Hello

Not really an issue, but I can't find a mailing list for Verovio.  So, we are implementing a search engine based on MEI and Verovio. Our engine returns the Ids of elements that match the search pattern, and we went to highlight these elements.

We can access each element in the SVG DOM. It features a class="note", so I assume that there is some kind of CSS somewhere. The question is: how can we dynamically change the display properties of this element, putting the color in red for instance, or whatsoever.

(BTW: is there a method to get the SVG DOM instead of a serialized representation?)

Thanks a lot for your help

Philippe

----

Example: 
<g xmlns="http://www.w3.org/2000/svg" class="note" id="d1e133">
								<use xlink:href="#E0A3" xmlns:xlink="http://www.w3.org/1999/xlink" x="4119" y="1620" height="720px" width="720px"/>
								<rect x="4119" y="1642" width="20" height="608" rx="0" style="stroke-width: 0;"/>
								<g class="verse" id="verse-000000061369036">
									<g class="syl" id="syl-000000052066890">
										<text x="4052" y="2980" dx="0" dy="0" font-size="0px">
											<tspan font-family="Garamond" font-size="405px">O</tspan>
										</text>
									</g>
								</g>
							</g>

**Comment by ahwitz** [comment]
Philippe,

To answer your SVG DOM question first: if you append the string that Verovio's loadData function returns to an HTML element, it'll automatically be [parsed and manipulable](https://github.com/DDMAL/vida.js/blob/master/vida.js#L55). Otherwise, there's also the [Javascript DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) object.

Once you have it parsed, take a look [here](https://github.com/DDMAL/vida.js/blob/master/vida.js#L368) for (a messy version of) how we've done style manipulation in the past. If the SVG is appended to the DOM, you can use the native XML parsing/manipulation libraries in Javascript off the document object to access parts of the SVG. If it's not yet appended, you should be able to use the same methods off of the \<svg\> root.

From here, you can use low-level functions like [getAttribute](https://github.com/DDMAL/vida.js/blob/master/vida.js#L286) to manipulate them as you wish. Because jQuery maps onto these methods, you can also use high-level functions like [$().css](https://github.com/DDMAL/vida.js/blob/master/vida.js#L236) with the same selectors.

**Comment by rigaux** [comment]
Thanks a lot Andrew, it works just fine now.

Best

Philippe


2015-07-31 15:34 GMT+02:00 Andrew Horwitz <notifications@github.com>:

> Philippe,
>
> To answer your SVG DOM question first: if you append the string that
> Verovio's loadData function returns to an HTML element, it'll automatically
> be parsed and manipulable
> <https://github.com/DDMAL/vida.js/blob/master/vida.js#L55>. Otherwise,
> there's also the Javascript DOMParser
> <https://developer.mozilla.org/en-US/docs/Web/API/DOMParser> object.
>
> Once you have it parsed, take a look here
> <https://github.com/DDMAL/vida.js/blob/master/vida.js#L368> for (a messy
> version of) how we've done style manipulation in the past. If the SVG is
> appended to the DOM, you can use the native XML parsing/manipulation
> libraries in Javascript off the document object to access parts of the SVG.
> If it's not yet appended, you should be able to use the same methods off of
> the <svg> root.
>
> From here, you can use low-level functions like getAttribute
> <https://github.com/DDMAL/vida.js/blob/master/vida.js#L286> to manipulate
> them as you wish. Because jQuery maps onto these methods, you can also use
> high-level functions like $().css
> <https://github.com/DDMAL/vida.js/blob/master/vida.js#L236> with the same
> selectors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rism-ch/verovio/issues/132#issuecomment-126693021>.
>



-- 
Cordialement / Regards

P. Rigaux
