### ISSUE TITLE
Defective rendering on Firefox

### ISSUE THREAD

**Issue by lguariento** [rism-ch/verovio#138]
Hello,

I have a strange rendering problem of .mei files:
![rendering](https://cloud.githubusercontent.com/assets/10143842/9383364/5b9cde1a-4740-11e5-956b-204c0267a861.jpg)

Anybody knows how to resolve it? This shows like that on Firefox 40 (on OSX 10.10.5), while on Google Chrome and Safari it renders properly.

Thanks

**Comment by lpugin** [comment]
This is quite likely a conflict with a css. It happens with Bootstrap. Try adding

```
svg:not(:root) {
  overflow: inherit; 
}
```

**Comment by lpugin** [comment]
Also, double check that this page works with your version of Firefox (it does with 40.0.2)
http://www.verovio.org/hello-mei-world.html

**Comment by lguariento** [comment]
Yes, the 

svg:not(:root) {
  overflow: inherit; 
}

solved the problem!
Thanks

**Comment by craigsapp** [comment]
This also worked for me.  The problem was indirectly related to Bootstrap.  I was using a style file generated from Bootstrap (but not Bootstrap directly).  In that file was the rule:

```css
svg:not(:root) {
    overflow: hidden;
}
```

So the solution is to either delete that rule if you find it, or make sure that your CSS file with the correction is loaded onto the page *after* the one which contains `overflow: hidden;`.
