### ISSUE TITLE
Feature request: Fingering

### ISSUE THREAD

**Issue by palgranum** [rism-ch/verovio#1422]
This has been raised before, but issues have been closed:
https://github.com/rism-ch/verovio/issues/803

**Comment by craigsapp** [comment]
Here is an example of how I do fingering:

<img width="269" alt="Screen Shot 2020-04-17 at 00 19 47" src="https://user-images.githubusercontent.com/3487289/79542822-28905a80-8041-11ea-943a-a986255ae276.png">


```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-04-17T00:12:56" version="2.7.0-dev-9b84e3d">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001834540875">
    <score xml:id="score-0000000974994227">
     <scoreDef xml:id="scoredef-0000000788044845" midi.bpm="400">
      <staffGrp xml:id="staffgrp-0000000813841722" symbol="brace" bar.thru="true">
       <staffDef xml:id="staffdef-0000001051038130" n="1" lines="5">
        <clef xml:id="clef-0000001040102829" shape="G" line="2" />
       </staffDef>
       <staffDef xml:id="staffdef-0000000552135769" n="2" lines="5">
        <clef xml:id="clef-0000001747259247" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001533481926" n="1">
        <layer xml:id="layer-L1F3N1" n="1">
         <chord xml:id="chord-L6F3" dur="1">
          <note xml:id="note-L6F3S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L6F3S2" oct="5" pname="e" accid.ges="n" />
          <note xml:id="note-L6F3S3" oct="5" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <staff xml:id="staff-0000001603969008" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <chord xml:id="chord-L6F1" dur="1">
          <note xml:id="note-L6F1S1" oct="3" pname="c" accid.ges="n" />
          <note xml:id="note-L6F1S2" oct="3" pname="e" accid.ges="n" />
          <note xml:id="note-L6F1S3" oct="3" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <dir xml:id="dir-L6F2" type="fingering" place="below" staff="2" startid="#note-L6F1S3">
        <rend xml:id="rend-0000000341693591" fontsize="x-small" fontstyle="normal">1</rend>
       </dir>
       <dir xml:id="dir-L6F2" type="fingering" place="below" staff="2" startid="#note-L6F1S2">
        <rend xml:id="rend-0000001148055958" fontsize="x-small" fontstyle="normal">3</rend>
       </dir>
       <dir xml:id="dir-L6F2" type="fingering" place="below" staff="2" startid="#note-L6F1S1">
        <rend xml:id="rend-0000000140049091" fontsize="x-small" fontstyle="normal">5</rend>
       </dir>
       <dir xml:id="dir-L6F4" type="fingering" place="above" staff="1" startid="#note-L6F3S1">
        <rend xml:id="rend-0000001875239719" fontsize="x-small" fontstyle="normal">1</rend>
       </dir>
       <dir xml:id="dir-L6F4" type="fingering" place="above" staff="1" startid="#note-L6F3S2">
        <rend xml:id="rend-0000001976498214" fontsize="x-small" fontstyle="normal">3</rend>
       </dir>
       <dir xml:id="dir-L6F4" type="fingering" place="above" staff="1" startid="#note-L6F3S3">
        <rend xml:id="rend-0000001237905050" fontsize="x-small" fontstyle="normal">5</rend>
       </dir>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

Further refinements could be added, as mentioned in #803, such as placing fingerings before/after notes (and accidentals attached to the notes) rather than only above/below notes.

Also, the stacking order of the fingerings is fragile, since the ordering is controlled by the position between siblings (and moving above/below the staff will reverse the order unless the sibling order is also reversed).   Maybe a stacking system for fingering similar to that of figured bass should be implemented.

One graphical problem is that the left edge of the finger number is placed at the center of notehead, but preferably the center of the finger number should centered to the center of the note.  If there is more than one fingering on a chord, perhaps the numbers in the group should be left-justified to each other, but then the composite group should be centered on the notehead.

**Comment by lpugin** [comment]
> This has been raised before, but issues have been closed:

Yes, because this is a too generic feature request. A music notation feature missing is not an issue, at least not the one we want to have listed here as a GitHub issue. These should be used for tracking more refined problems. This is why the issue was closed, because adding such issues is not really helpful. What would be more helpful would be a PR implementing it ;-)

Implementing a basic `<fing>` support would not be too complicated. A good example to follow could be `<breath>`. If you want to support extenders (which we will want eventually), then `<dir>` or `<bracketSpan>` (simpler) would be the one to follow. (For more complex cases, for which @craigsapp gave examples, then we would need to implement `<fingGrp>`.)

Closing again, speak up if help is needed for the implementation.
