### ISSUE TITLE
channel question?

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1456]
@lpugin  Is there any interface to get the channel information of each note?

**Comment by craigsapp** [comment]
In `<instrDef>`, there is an attribute `@midi.channel`:

https://music-encoding.org/guidelines/v4/elements/instrdef.html

`<instrDef>` should be a child element of `<staffDef>` when present in the MEI file.

In general MIDI output from verovio is used on the web with [WildWebMidi](https://github.com/zz85/wild-web-midi) which limits to a single instrument (otherwise loading multiple soundfonts on the web would take more time), so I don't know if `staffDef/instrDef@midi.channel` is observed or ignored by verovio (@rettinghaus might have added it the past year, however).

**Comment by lpugin** [comment]
Yes, `midi.channel` is taken into account in the MIDI output.
