### ISSUE TITLE
Mensural Notation: missing element <ligature>

### ISSUE THREAD

**Issue by rklugseder** [rism-ch/verovio#149]

**Comment by craigsapp** [comment]
Marcin just asked for this feature as well, but for modern notation (so a ligature bracket rather than the ligature itself).

How should ligature brackets be encoded?  In a manner similar to `<slur>`s?  I am vaguely remembering asking about this last year in Florence while jet-lagged.  They would  implemented with an element similar to but not `<line>`  in modern notation?

![screen shot 2016-08-11 at 2 41 58 pm](https://cloud.githubusercontent.com/assets/3487289/17588870/d751ee88-5fd1-11e6-875d-dc82b11fdf42.png)

**Comment by lpugin** [comment]
See this request for a ```ligatureSpan``` element: https://github.com/music-encoding/music-encoding/issues/274

**Comment by lpugin** [comment]
BTW, I think the original request is support for ```ligature``` elements in mensural notation (and not in CNM)

**Comment by lpugin** [comment]
General feature request
