### ISSUE TITLE
[Question] download binary MIDI

### ISSUE THREAD

**Issue by axgeertinger** [rism-ch/verovio#1513]
I know it's not really a Verovio question, but perhaps someone here has some experience to share. I am trying to make the base 64 encoded MIDI generated by Verovio downloadable as binary MIDI. I don't seem to be able to produce a valid MIDI file, however. Tried the following, among other things (using the file saver also used by the Verovio viewer: https://www.verovio.org/javascript/FileSaver.min.js):
```
var base64midi = vrvToolkit.renderToMIDI();
var binaryMidi = atob(base64midi);
saveAs(new Blob([binaryMidi], {type: "audio/midi"}), "midi_atob.mid");
```
Here's an example of a base 64 encoding generated by Verovio:

`TVRoZAAAAAYAAQACAHhNVHJrAAAACwD/UQMCUtwA/y8ATVRyawAAAR54kDdag2CQNwAAkDdag2CQNwAAkDVag2CQNQAAkDpag2CQOgAAkDlagXCQOQAAkDdagXCQNwAAkDlag2CQOQAAkDdag2CQNwCDYJA3WoNgkDcAAJA6WoNgkDoAAJA8WoVQkDwAAJA6WoFwkDoAAJA8WoNgkDwAAJA+WoNgkD4AAJA6WoNgkDoAg2CQOlqDYJA6AACQPFqDYJA8AACQPlqDYJA+AACQOlqDYJA6AACQPFqDYJA8AACQOlqBcJA6AACQOVqBcJA5AACQN1qDYJA3AINgkDdag2CQNwAAkDdag2CQNwAAkDVag2CQNQAAkDpag2CQOgAAkDlagXCQOQAAkDdagXCQNwAAkDlag2CQOQAAkDdajwCQNwAA/y8A`

The decoding service at https://base64.guru/converter/decode converts it to an apparently valid, playable MIDI file (attached), while the code above does not (also attached), at least not on my system. The base64.guru service detects the character encoding to be ISO-8859-1, while atob() probably assumes ASCII. Could that be an issue? Probably not. So I guess the is problem something completely different. 
[binary_midi_attempts.zip](https://github.com/rism-ch/verovio/files/4819824/binary_midi_attempts.zip)

**Comment by craigsapp** [comment]
midi_atob.mid has character translations such as 0xff changing into 0xc3 0xbf, so the problem is that a UTF-8 encoding was applied to the original MIDI bytes.  So try using `charset=binary` to see if that avoids messing up the bytes:

```
var base64midi = vrvToolkit.renderToMIDI();
var binaryMidi = atob(base64midi);
saveAs(new Blob([binaryMidi], {type: "application/octet-stream; charset=binary"}), "midi_atob.mid");
```

-------------------

Here is someone who documents their saga in figuring out how to save MIDI files from a web browser:

https://blog.logrocket.com/binary-data-in-the-browser-untangling-an-encoding-mess-with-javascript-typed-arrays-119673c0f1fe/

------------------

Looking at this Javascript code: https://github.com/sergi/jsmidi/blob/master/midi.js,
I would suspect that something like this might work:

```
window.open("data:audio/midi;base64," + b64mididata,
"My MIDI file", "resizable=yes,scrollbars=no,status=no");
```

What that does may depend on the web browser and/or user settings.  It is opening a MIDI file into a browser page, so some browsers may open a page with a play button, while others may open a save window if it does not know what to do with MIDI.

**Comment by axgeertinger** [comment]
Thank you so very much, Craig! That was extremely helpful. To summarize my results:
1) Changing type from "audio/midi" to "application/octet-stream; charset=binary" didn't seem to change anything.
2) Opening the base64 data in a new browser window worked, but as you mentioned behaviour (playing in the browser or download) will vary.
3) The story at logrocket.com was the key. This works nicely:
```
var binaryMidi = atob(base64midi);
var u16 = new Uint16Array(binaryMidi.length);
var u8 = new Uint8Array(binaryMidi.length);
for(var i=0;i<binaryMidi.length;i++){
  u16[i] = binaryMidi[i].charCodeAt(0);
  u8[i] = u16[i];
}
saveAs(new Blob([u8], {type:'audio/midi'}),"midi.mid");

```
You made my day. Thanks once again :-)
