### ISSUE TITLE
Group spacing support

### ISSUE THREAD

**Issue by kseniaosipova** [rism-ch/verovio#1526]
There would be a good option for improving rendering quality, to have a parameter for setting the spacing between groups of instruments (e.g. --spacing-group):

![image](https://user-images.githubusercontent.com/60135178/86469963-bde6e500-bd3a-11ea-90d2-bb9e03217048.png)

Also, for chamber music, to have parameters to control:

- spacing within individual staff group of the main instrument:

![image](https://user-images.githubusercontent.com/60135178/86470104-03a3ad80-bd3b-11ea-8750-b6a17851de1e.png)

- spacing between staff groups of the main instruments:

![image](https://user-images.githubusercontent.com/60135178/86470223-46658580-bd3b-11ea-8377-7a5d4ec306eb.png)

- spacing between staff groups of the main instruments and other instruments:

![image](https://user-images.githubusercontent.com/60135178/86470257-5bdaaf80-bd3b-11ea-930c-56c876ec27f9.png)

**Comment by craigsapp** [comment]
Yes, spacing control of groups would be good to have as an additional control to spacing options for the staff and system:

```
 --spacing-staff <i>               The staff minimal spacing in MEI units (default: 8; min: 0; max: 24)
 --spacing-system <i>              The system minimal spacing in MEI units (default: 3; min: 0; max: 12
 --spacing-group <i>               The group minimal spacing in MEI units (default: 3; min: 0; max: 12
```

With min/max/default to be determined.

Adding such control would be useful for creating dynamic vertical adjustments for orchestral scores, as well as soloist/accompanist scores and other grouped scores.

**Comment by craigsapp** [comment]
The basic implementation could be identical to the current staff/system spacing option.

There are other things to think about in the meantime.

In the first example, there are three groups, but also additional complications:

<img width="936" alt="Screen Shot 2020-07-03 at 6 21 50 AM" src="https://user-images.githubusercontent.com/3487289/86473298-8570e800-bcf5-11ea-8784-3a9b5c45d6c0.png">

The first complication is that the harp part is on the [grand staff](https://en.wikipedia.org/wiki/Staff_(music)#Grand_staff).  Ideally the spacing controls between these two staves would have a separate control.   I can thing of two: (1) the minimum spacing between the two sub-staves, and (2) the maximum spacing that is allowed when the `--justify-vertically` option is used.  For number 2, it would be useful to limit the maximum space padding between grand-staff staves and/or have the vertical justification algorithm assign less padding between grand staff staves when it vertically stretches the spacing of the staves/systems/groups on a page.  Control (1) is probably not necessary, but may be useful in some cases.  Control (2) would be more useful as is demonstrated in this example, where the two staves of the harp part are more closely spaced than the two staves of the woodwind group.

Is there a way of indicating grand-staffness in MEI?  In MusicXML it is always explicit, since there is an extra hierarchy to the staves that MEI does not have, since MusicXML is encoded by part rather than staff.

The second complication is that the first and second violins are in a sub-group.  Would `--spacing-group` be limited to first-level groupings only, or would it be allowed to apply to nested groups?  Or would there be a second-level group spacing option, such as `--spacing-group-2` to allow spacing control at the second level of nested grouping?  In this particular case there should be no secondary group spacing, so if there were a `--spacing-group-2` option, the default should be 0.

**Comment by lpugin** [comment]
> The second complication is that the first and second violins are in a sub-group. Would --spacing-group be limited to first-level groupings only, or would it be allowed to apply to nested groups? Or would there be a second-level group spacing option, such as --spacing-group-2 to allow spacing control at the second level of nested grouping? In this particular case there should be no secondary group spacing, so if there were a --spacing-group-2 option, the default should be 0. 

I am not a big fan of options with `-2`. What about `--spacing-sub-group`?

**Comment by craigsapp** [comment]
Yes, `--spacing-sub-group` is good.  That would limit to either only the second-level group, or be applied to all sub-groups, but that is probably not a problem.

**Comment by craigsapp** [comment]
This example is quite complicated:

<img width="901" alt="Screen Shot 2020-07-03 at 11 43 50 AM" src="https://user-images.githubusercontent.com/3487289/86492280-794f4f80-bd22-11ea-944b-6eeca7791181.png">

There are three groups: each group is defined by the presence of the "Mäßig rasch" above the group as well as the system beaming pattern, in other words, with the Rezitation part in a group by itself.

I do not see that the separation between the Rezitation group and the instrumental group above it would be anything different from a standard group spacing, and likewise for the Rezitaion/Klavier group spacing.

For the spacing between the Rezitation and the Klavier group, this is extra wide due to the musical content between them which is pushing the staves apart.  Verovio only controls the minimum distance between staves/systems, and in the future groups.  It does not/should not allow controls for the maximum distance when the staves need to be pushed apart to avoid notation collisions.

Keep in mind that the example you give was manually typeset.   The tight spacing between the piano and voice parts is difficult to achieve automatically since the text of the tempo marking in the piano part is vertically getting into the space of the text for the vocal part.  In general this is not good typesetting since it reduces the readability for both the pianist and the singer when reading from the score, and the computer cannot be given clear-cut rules for how to compress music into a tight configuration.  Such tight spacing is less common in computer-typeset music due to this problem.  For such tight spacing, there would probably need to be an option that allows tight kerning of unrelated text between the staves.  And there is also a secondary problem that the horizontal spacing of the music may need to be tweaked in order to allow the tight kerning of the text between the staves as is done in this example, which would also be complicated to calculate automatically.

Spacing between the two staves of the piano part is problematic for the computer in this case.  Since the music has cross-staff beaming, there is no clear way to decide the spacing of the staves, other than to limit the minimum space (for the entire work). Probably a good automatic rule would be to avoid placing the beams of notes on the opposite staff inside of the other staff, as done here, where the mimum space is two diatonic steps above the beam.

**Comment by kseniaosipova** [comment]
The point that, in chamber music, the main instrument/instruments have larger staves/larger elements comparing to the other instruments above, so that make sense to set 
the spacing between the large staves and small staves - (proportionally) bigger than the spacing between groups of small staves; 
![image](https://user-images.githubusercontent.com/60135178/86508633-ed9cf800-bde1-11ea-8e88-acd43fa4d38c.png)
(in the example above spacing between harpa and violoncello is different from a standard group spacing, and not because of the musical content)
the spacing between the groups of large staves (piano and voice - (proportionally) bigger than the spacing between groups of small stave as well; 
the spacing within a group of large staves (piano) - (proportionally) bigger than the staff spacing of small staves
![image](https://user-images.githubusercontent.com/60135178/86508579-65b6ee00-bde1-11ea-80f0-7387a05b55d5.png)
(here Veriovio renders it also with a bigger space, but it also could change from system to system, so it would be better to control the min spacing here as well)

**Comment by craigsapp** [comment]
This one seems fairly standard:

<img width="1176" alt="Screen Shot 2020-07-04 at 8 03 04 AM" src="https://user-images.githubusercontent.com/3487289/86515336-0353f280-bdcd-11ea-902d-df7f750d8032.png">

There are two groups, so the spacing between the groups would be controlled with `--spacing-group`.

For staves that are smaller, the `--spacing-staff` value should be using smaller units proportional to the scaling size of the staves (which verovio seems to be doing based on the second example).

------------

For the second example, the spacing between the two staves in the piano part is excessively wide.  This is the special case of a grand staff, which would be ideal to handle separately from other inter-staff spacings.  In order to do this, the grand staff needs to be marked in an explicit way.

Otherwise, the spacing between the large staves is physically larger than the spacing between the smaller staves, so verovio is proportionally scaling the `--spacing-staff` units according to the sizes of the staves.  The `--spacing-group` control would allow adding more space between the piano and the other parts.  The MEI data probably currently does not group the three instrumental staves, but it should so that the `--spacing-group` can be applied with the desired effect.  Also, the standard style would be to draw the barlines between the three instruments, similar to the first example (and to do this requires placing them in their own group).

The wide spacing between the violin and viola is due to the `mf` dynamics placement:

<img width="518" alt="Screen Shot 2020-07-04 at 8 25 26 AM" src="https://user-images.githubusercontent.com/3487289/86515791-73b04300-bdd0-11ea-8f84-c13f71fddde9.png">

In a standard typesetting of the music, the `mf` would be placed before the note and moved up to decrease the needed space between the staves.  This can currently be done manually in MEI/verovio, but not with any refined control:

<img width="532" alt="Screen Shot 2020-07-04 at 8 26 41 AM" src="https://user-images.githubusercontent.com/3487289/86515815-9b9fa680-bdd0-11ea-97ea-1fe33fab4614.png">


The adjusted placement is done with a right-justification of the dynamic:

```xml
       <dynam xml:id="dynam-L14F6" staff="1" tstamp="2.000000" vgrp="100">
             <rend xml:id="rend-0000001704439776" halign="right" fontsize="large" fontweight="bold">mf </rend>
       </dynam>
```

I had to add a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) after the `mf` in order to add extra horizontal clearance from the notehead, so verovio did not auto-detect the dynamic to set its font correctly (related to issue https://github.com/rism-ch/verovio/issues/1117, but I should create a new issue specifically to allow a non-breaking space to be treated similar to a regular space when auto-identifying dynamic symbols).

Here is the MEI data for the bottom example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-07-04T08:27:25" version="3.0.0-dev-5706f96-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title xml:id="title-L1" analog="humdrum:Xfi" type="translated">vertical spacing demo</title>
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001956175476">
    <score xml:id="score-0000001731203839">
     <scoreDef xml:id="scoredef-0000000336540058">
      <staffGrp xml:id="staffgrp-0000000384240692" bar.thru="false">
       <staffDef xml:id="staffdef-0000002099532944" n="1" lines="5">
        <label xml:id="label-L4F5">Violin</label>
        <clef xml:id="clef-L5F5" shape="G" line="2" />
        <keySig xml:id="keysig-L6F5" sig="3f" />
        <meterSig xml:id="metersig-L7F5" count="3" unit="4" />
       </staffDef>
       <staffDef xml:id="staffdef-0000001109150344" n="2" lines="5">
        <label xml:id="label-L4F3">Viola</label>
        <clef xml:id="clef-L5F3" shape="C" line="3" />
        <keySig xml:id="keysig-L6F3" sig="3f" />
        <meterSig xml:id="metersig-L7F3" count="3" unit="4" />
       </staffDef>
       <staffDef xml:id="staffdef-0000000300922137" n="3" lines="5">
        <label xml:id="label-L4F1">Violoncello</label>
        <clef xml:id="clef-L5F1" shape="F" line="4" />
        <keySig xml:id="keysig-L6F1" sig="3f" />
        <meterSig xml:id="metersig-L7F1" count="3" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L3F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000634046861" n="1">
        <layer xml:id="layer-L3F5N1" n="1">
         <mRest xml:id="mrest-L9F5" />
        </layer>
       </staff>
       <staff xml:id="staff-0000000822615045" n="2">
        <layer xml:id="layer-L3F3N1" n="1">
         <mRest xml:id="mrest-L9F3" />
        </layer>
       </staff>
       <staff xml:id="staff-0000002073184780" n="3">
        <layer xml:id="layer-L3F1N1" n="1">
         <mRest xml:id="mrest-L9F1" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L10" n="2">
       <staff xml:id="staff-L10F5N1" n="1">
        <layer xml:id="layer-L10F5N1" n="1">
         <rest xml:id="rest-L11F5" dur="4" />
         <note xml:id="note-L14F5" dur="4" oct="3" pname="g" accid.ges="n" />
         <note xml:id="note-L15F5" dur="4" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L10F3N1" n="2">
        <layer xml:id="layer-L10F3N1" n="1">
         <rest xml:id="rest-L11F3" dur="4" />
         <note xml:id="note-L14F3" dur="4" oct="3" pname="g" accid.ges="n" />
         <note xml:id="note-L15F3" dur="4" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L10F1N1" n="3">
        <layer xml:id="layer-L10F1N1" n="1">
         <rest xml:id="rest-L11F1" dur="4" />
         <note xml:id="note-L14F1" dur="4" oct="3" pname="g" accid.ges="n" />
         <note xml:id="note-L15F1" dur="4" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <dynam xml:id="dynam-L14F6" staff="1" tstamp="2.000000" vgrp="100">
        <rend xml:id="rend-0000001704439776" halign="right" fontsize="large" fontweight="bold">mf </rend>
       </dynam>
       <dir xml:id="dir-L14F5" place="above" staff="1" tstamp="2.000000">sostenuto</dir>
       <dynam xml:id="dynam-L14F4" staff="2" tstamp="2.000000" vgrp="100">mf</dynam>
       <dir xml:id="dir-L14F3" place="above" staff="2" tstamp="2.000000">sostenuto</dir>
       <dynam xml:id="dynam-L14F2" staff="3" tstamp="2.000000" vgrp="100">mf</dynam>
      </measure>
      <measure xml:id="measure-L16" n="3">
       <staff xml:id="staff-L16F5N1" n="1">
        <layer xml:id="layer-L16F5N1" n="1">
         <note xml:id="note-L17F5" dots="1" dur="4" oct="5" pname="g" accid.ges="n" />
         <note xml:id="note-L18F5" dur="8" oct="5" pname="d" accid.ges="n" />
         <note xml:id="note-L19F5" dur="4" oct="5" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L16F3N1" n="2">
        <layer xml:id="layer-L16F3N1" n="1">
         <note xml:id="note-L17F3" dots="1" dur="4" oct="4" pname="g" accid.ges="n" />
         <note xml:id="note-L18F3" dur="8" oct="4" pname="d" accid.ges="n" />
         <note xml:id="note-L19F3" dur="4" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L16F1N1" n="3">
        <layer xml:id="layer-L16F1N1" n="1">
         <note xml:id="note-L17F1" dots="1" dur="4" oct="3" pname="g" accid.ges="n" />
         <note xml:id="note-L18F1" dur="8" oct="3" pname="d" accid.ges="n" />
         <note xml:id="note-L19F1" dur="4" oct="3" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by th-we** [comment]
The requirements for minimum distances should be covered with the following options:

* `--spacing-staff`: "Default" minimum space between any staves
* `--spacing-bracket-group`: Overrides `--spacing-staff` when we're *within* a `<staffGrp>` with `@symbol='bracket'` or `'bracketsq'`.
* `--spacing-brace-group`: Overrides `--spacing-staff` when we're *within* a `<staffGrp>` with `@symbol='brace'`. Like this, we can handle grand staves (like for piano and harp). Right now, there does not seem to be any other canonical way of identifying staves that belong to a grand staff with MEI.
* --`spacing-system`: Overrides `--spacing-staff` between systems. At the moment, this option seems to be adding a fixed amount of space on the distance determined to avoid collisions. Adding space on top of the minimum space should be done during justification, which is a different issue.

All minimum distances within a system should scale proportionally with the size of the staves. Between two staves of different sizes, the scale of the larger staff should be used. `--spacing-system` should however not be proportionally altered.  Even if there are staves of non-default size at the top/bottom of systems, it should always be based on the standard vertical unit ("vu").

**Comment by kseniaosipova** [comment]
Hi @lpugin , what do you think about the last approach?

**Comment by lpugin** [comment]
Sounds good to me, thanks. (Please make sure the ` --justify-systems-only` option behavior is preserved)

**Comment by th-we** [comment]
(Edited my last comment to make clear that between systems, `--spacing-staff` should not be applied.)

**Comment by rettinghaus** [comment]
@lpugin this feature is implemented, so I think this issue can be closed.
