### ISSUE TITLE
Usage of transposition

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1769]
Now I have added the webpage displaying the staff to the iOS project, and by passing midi data, use (var vrvToolkit = new verovio.toolkit(); )
vrvToolkit.loadData(mididata); 
to display the staff

How do I use on this basis -- transpose parameter to transpose this staff?

**Comment by craigsapp** [comment]
You cannot load MIDI data into verovio, only export it.  So do you have an error when running `vrvToolkit.loadData(mididata);`?

**Comment by yangyangnote** [comment]
@craigsapp  At the beginning I thought so too, but after practice, there is no error, and the staff can be displayed directly. I guess I completed the conversion of midi files into mei files in loaddata.

**Comment by yangyangnote** [comment]
@craigsapp  Sorry I made a mistake. I loaded a MusicXml file, which may be converted into a mei file in loaddata, not a midi file. How can I transpose on this basis?

**Comment by craigsapp** [comment]
You are mentioning an iOS project, which I would assume is C++, but the example code you give is in Javascript, so here are examples of transposing using the Javascript toolkit.  The testing webpage used to create the examples is at the bottom of this message.

To set the transposition for the music, add a `transpose` entry to the verovio options:

```javascript

var vrvOptions = {
        transpose: "M2",
        scale: 60,
        header: "none",
        pageHeight: 6000,
        adjustPageHeight: 1,
        pageWidth: 2100,
        spacingStaff: 12,
        spacingSystem: 12
}
```

Here is the test example music with no transpose given (just C/Do major triad):

<img width="424" alt="Screen Shot 2020-10-21 at 1 54 19 PM" src="https://user-images.githubusercontent.com/3487289/96786680-7c3f8000-13a5-11eb-8cf0-8cc87f1f043d.png">

Setting `transpose: "M2"` will transpose the music up a major second from C/Do to D/Re:

<img width="471" alt="Screen Shot 2020-10-21 at 2 06 08 PM" src="https://user-images.githubusercontent.com/3487289/96787448-9cbc0a00-13a6-11eb-9d0b-d2a3cc7f586f.png">

To go down a minor second from C/Do to Si/B:

<img width="503" alt="Screen Shot 2020-10-21 at 2 00 04 PM" src="https://user-images.githubusercontent.com/3487289/96786887-bd379480-13a5-11eb-9692-b47a217d416f.png">

Common intervals:  `m3` = minor third, `M3` = major 3rd, `P4` = perfect fourth, `P5` = perfect fifth, `d5` = diminished fifth, `A4` = augmented fourth.

You can also give semitone steps, with 1 being one semitone, 2 being two semitones, etc.  This method is less precise, and the computer will make an automatic calculating to minimize the number of accidentals in the target key signature.  

For example the integer transpostion "1" will display in D-flat major:

<img width="553" alt="Screen Shot 2020-10-21 at 2 03 15 PM" src="https://user-images.githubusercontent.com/3487289/96787196-346d2880-13a6-11eb-833a-01fd8e183ef9.png">

This is equivalent to going up a minor second:

<img width="486" alt="Screen Shot 2020-10-21 at 2 04 16 PM" src="https://user-images.githubusercontent.com/3487289/96787284-5070ca00-13a6-11eb-9a51-5524f020cc94.png">

If you need to transpose to C-sharp major, then you cannot use integers, but must use the full musical interval, which in this case is "A1" for an augmented unison:

<img width="511" alt="Screen Shot 2020-10-21 at 2 05 12 PM" src="https://user-images.githubusercontent.com/3487289/96787367-75653d00-13a6-11eb-9c31-0a2e3c2d4d21.png">

(`a1` and `A1` are the same, but `m2` and `M2` are not equivalent).

--------------

You can also give the tonic note of the new key.  For example "E" means to transpose to E major (or minor, since the mode will not be changed).  This feature requires that the music contain key information which is now always present in MusicXML data.  It can also be incorrect, which may cause problems, so use this option with care in an automatic situation.

<img width="529" alt="Screen Shot 2020-10-21 at 2 07 00 PM" src="https://user-images.githubusercontent.com/3487289/96787612-e6a4f000-13a6-11eb-8c13-9ecffe3f727c.png">

F-sharp major:

<img width="549" alt="Screen Shot 2020-10-21 at 2 08 53 PM" src="https://user-images.githubusercontent.com/3487289/96787660-fae8ed00-13a6-11eb-84ed-e5973f64b441.png">

Equivalent to a transposition of `A4`, and G-flat, which is equivalent to `d5`:

<img width="477" alt="Screen Shot 2020-10-21 at 2 10 27 PM" src="https://user-images.githubusercontent.com/3487289/96787799-384d7a80-13a7-11eb-884c-f3241c64ab76.png">

Notice that this method moves to the closest tonic.  To force G-flat major above, add a `+`:

<img width="538" alt="Screen Shot 2020-10-21 at 2 11 22 PM" src="https://user-images.githubusercontent.com/3487289/96787847-4dc2a480-13a7-11eb-8fe3-26be2df55cc8.png">

To go another octave above, add two `++`:

<img width="498" alt="Screen Shot 2020-10-21 at 2 11 50 PM" src="https://user-images.githubusercontent.com/3487289/96787882-5f0bb100-13a7-11eb-9a64-9f21de9e440e.png">

-------------------

Here is the test HTML file used to create the above example:

```html
<html>
<head>
<title>Transposition test</title>
</head>
<body>

<div style="color:blue; font-size:2rem;" id="parameters"></div>
<div id="example"></div>

<script>
var vrvToolkit;
var Module = {
	onRuntimeInitialized: function() {
		vrvToolkit = new verovio.toolkit();
		prepareExample("example");
	}
};
</script>

<script src="https://verovio-script.humdrum.org/scripts/verovio-toolkit-wasm.js"></script>

<script>

var vrvOptions = {
	transpose: "++Gb",
	scale: 60,
	header: "none",
	pageHeight: 6000,
	adjustPageHeight: 1,
	pageWidth: 2100,
	spacingStaff: 12,
	spacingSystem: 12
}

function prepareExample(targetid) {
	var delement = document.querySelector("#musicxml-data");
	var data = delement.textContent;
	var svg = vrvToolkit.renderData(data, vrvOptions);
	var element = document.querySelector("#" + targetid);
	element.innerHTML = svg;
	var pelement = document.querySelector("#parameters");
	var output = 'transpose: "' + vrvOptions.transpose + '"';
	pelement.innerHTML = output;
}

</script>

<script type="text/x-musicxml" id="musicxml-data"><?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work>
    <work-title>Title</work-title>
    </work>
  <identification>
    <creator type="composer">Composer</creator>
    <encoding>
      <software>MuseScore 3.4.2</software>
      <encoding-date>2020-10-21</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7.05556</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1683.36</page-height>
      <page-width>1190.88</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <credit page="1">
    <credit-words default-x="595.44" default-y="1626.67" justify="center" valign="top" font-size="24">Title</credit-words>
    </credit>
  <credit page="1">
    <credit-words default-x="1134.19" default-y="1526.67" justify="right" valign="bottom" font-size="12">Composer</credit-words>
    </credit>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="265.51">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>0.00</left-margin>
            <right-margin>811.98</right-margin>
            </system-margins>
          <top-system-distance>170.00</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <note default-x="83.07" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>whole</type>
        </note>
      <note default-x="83.07" default-y="-40.00">
        <chord/>
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>whole</type>
        </note>
      <note default-x="83.07" default-y="-30.00">
        <chord/>
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>whole</type>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
</script>

</body>
</html>
```

**Comment by yangyangnote** [comment]
Thank you very much for your help, I have realized the transposition function by passing in the value of transpostion, -12...1...12 @craigsapp
