### ISSUE TITLE
Lindenbaum example

### ISSUE THREAD

**Issue by uliska** [rism-ch/verovio#1838]
Some nitpicks regarding the "Lindenbaum" example used in the Verovio MEI viewer:

* Schubert's cycle is called "Winterreise", not "Die Winterreise"
* The setting is not an excerpt, but an arrangement
* The arrangement is by Friedrich Silcher, written in 1846 for four male voices, the version for voice and piano being a secondary version of Silcher's setting
* Silcher's setting is titled "Am Brunnen vor dem Tore", with any references to Müller's cycle and title removed

Reference: <https://de.wikipedia.org/wiki/Am_Brunnen_vor_dem_Tore>

**Comment by lpugin** [comment]
Thanks! Would you be able to make a PR with these changes? The file in question is https://github.com/rism-ch/verovio.org/blob/gh-pages/examples/downloads/Schubert_Lindenbaum.mei in the https://github.com/rism-ch/verovio.org repository. (I am closing the issue here.)

**Comment by craigsapp** [comment]
>  in the https://github.com/rism-ch/verovio.org repository. (I am closing the issue here.)

I think you mean in the MEI sample encodings repository?
https://github.com/music-encoding/sample-encodings

Specifically this file:
https://github.com/music-encoding/sample-encodings/blob/master/MEI_4.0/Music/Complete_examples/Schubert_Lindenbaum.mei

I was the original encoder of this music in 2004:
https://kern.humdrum.org/cgi-bin/ksdata?file=erk205.krn&l=users/craig/songs/erk/liederschatz/band2&format=kern
which was then converted into MusicXML and then to MEI and then copied over to verovio as a demo piece.


This work was encoded from
Deutscher Liederschatz, Ludwig Erk, ed. Published by C.F. Peters. published in the 1880's (I own an original copy):
<img width="152" alt="Screen Shot 2020-11-19 at 7 35 57 AM" src="https://user-images.githubusercontent.com/3487289/99687795-eb0e0880-2a39-11eb-9929-4ea53ff01646.png">
Band II, Seite 5 song number 205:

https://ks.imslp.info/files/imglnks/usimg/6/68/IMSLP344359-SIBLEY1802.18663.641a-39087011120609vol._2_score.pdf
https://imslp.org/wiki/Erk's_Deutscher_Liederschatz_(Erk%2C_Ludwig)
https://github.com/music-encoding/sample-encodings/blob/master/MEI_4.0/Music/Complete_examples/Schubert_Lindenbaum.pdf

<img width="583" alt="Screen Shot 2020-11-19 at 7 38 14 AM" src="https://user-images.githubusercontent.com/3487289/99688083-3e805680-2a3a-11eb-8ce7-ad8cbdb1b74b.png">

The lyrics are by Müller in 1822:
https://www.tomoko-yamamoto.com/multimedia/schubert/Der_Lindenbaum_en.html

Original composition by Schubert:
https://www.youtube.com/watch?v=zC7gEVSgf9k
which is through-composed with piano interludes.

<img width="702" alt="Screen Shot 2020-11-19 at 7 52 41 AM" src="https://user-images.githubusercontent.com/3487289/99689776-404b1980-2a3c-11eb-82a0-3ffb8b9a8a18.png">

<img width="673" alt="Screen Shot 2020-11-19 at 7 52 49 AM" src="https://user-images.githubusercontent.com/3487289/99689786-42ad7380-2a3c-11eb-8016-98f7c5bf9ed7.png">


> The arrangement is by Friedrich Silcher, written in 1846 for four male voices, the version for voice and piano being a secondary version of Silcher's setting

Is there an online copy of the original Silcher arrangement (i.e., a scan)?

 I find the following credited to Silcher on IMSLP which is for solo voice and piano:

https://ks4.imslp.net/files/imglnks/usimg/a/a1/IMSLP09402-Franz_Schubert,_Wilhelm_M%C3%BCller_-_Der_Lindenbaum.pdf
https://imslp.org/wiki/Der_Lindenbaum_(Silcher,_Friedrich)

<img width="655" alt="Screen Shot 2020-11-19 at 8 16 39 AM" src="https://user-images.githubusercontent.com/3487289/99693122-dfbddb80-2a3f-11eb-85f7-9fb2bf84a3e0.png">

This is from:
https://imslp.org/wiki/Deutsche_Weisen_(Various)
edited by August Linder and published circa 1900 as another collection of songs.   Silcher does not seem to be credited in this edition, but there is no full scan of the edition on IMSLP.  The scan of the music does not credit Silcher in any case.

The Linder and Erk editions are clearly related, primarily due to the repeat of the last line of the poem, which Schubert did not do in the original.  Also the last note of the first phrase is moved to the third rather than tonic note of the chord, and of course both are in F.  The Erk arrangement is more faithful to the original Schubert version.



CPDL has a digital edition of the original Silcher arrangement (but it is dated 1902, so a reprint)
https://www.cpdl.org/wiki/index.php/Der_Lindenbaum_(Friedrich_Silcher)
https://www.cpdl.org/wiki/index.php/Volkslieder,_gesammelt_und_f%C3%BCr_vier_M%C3%A4nnerstimmen_gesetzt_(Friedrich_Silcher)
which has a link to the 1902 edition on IMSLP:
https://imslp.org/wiki/Volkslieder_gesammelt_und_f%C3%BCr_vier_M%C3%A4nnerstimmen_gesetzt_(Silcher,_Friedrich)

<img width="663" alt="Screen Shot 2020-11-19 at 8 41 15 AM" src="https://user-images.githubusercontent.com/3487289/99695945-04678280-2a43-11eb-9949-072546ee32f7.png">

<img width="650" alt="Screen Shot 2020-11-19 at 8 41 42 AM" src="https://user-images.githubusercontent.com/3487289/99696006-10ebdb00-2a43-11eb-8ae5-2c205c25ef52.png">

In this edition Silcher is credited with the arrangement:

<img width="540" alt="Screen Shot 2020-11-19 at 8 44 36 AM" src="https://user-images.githubusercontent.com/3487289/99696401-835cbb00-2a43-11eb-8456-4eb0e0f8564c.png">

This arrangement is in B-flat major.  But this edition is further from the Erk or Linder arrangements, which are also closer to the Schubert original.  It does have the repetition of the last line of the poem.

CPDL gives a citation for the 1846 original edition of this:
```
First published: 1846 in Volkslieder für vier Männerstimmen, Heft VIII, Op. 50, Tübingen: Laupp, no. 6
  2nd published: 1902 in Volkslieder, gesammelt und für vier Männerstimmen gesetzt, no. 21
```

If this is an exact copy of the 1846 edition, it is fairly different from the original Schubert and Erk edition, with the main common feature being the repeat of the last line of the poem.  There are rhythmic differences in some of the triplets which differentiate the editions as well, and the Erk edition being more faithful to the original Schubert rhythms.   The 1902 edition also has significant alteration of the melody that is not present in the Erk edition (only a few notes such as the last note in the first phrase).
