### ISSUE TITLE
Provide uninstall instructions

### ISSUE THREAD

**Issue by apacha** [rism-ch/verovio#1969]
I think it would be great to include instructions on how to complete uninstall verovio command line tools into the [build instructions](https://github.com/rism-ch/verovio/wiki/Building-instructions) (e.g., in case one wants a fresh restart).

Is it enough to `rm -rf /usr/local/bin/verovio`?

**Comment by craigsapp** [comment]
There are two locations for verovio on the system: the executable (that you mention) and the fonts, which are stored in `/usr/local/share/verovio`.   `/usr/local/bin/verovio` is a file, so you should avoid the habit of including `-r` when only deleting files, since that is a very dangerous option.   So to uninstall verovio from the system:

```bash
rm -f /usr/local/bin/verovio
rm -rf /usr/local/share/verovio
```

Maybe there should be an explanation about what files are copied where on the build instruction page, @lpugin? 

However, if you want to reinstall verovio, it is not necessary to delete anything to do a fresh install.   Just type `make install` again and the verovio executable and fonts will overwrite the previous files.

`make install` is needed whenever a new glyph is added to a font (otherwise there can be crashes in verovio, I think.  Or of course when a new font is added such as Leland, which is why you are asking this question 😉   Even if you are running verovio from `verovio/tools/verovio`, the system fonts need to match (unless you give a different location for the fonts with the `-r` or `--resources` option to use a non-default location).

-----------------

Along the same topic:

Occasionally there are problems with updates necessary to the `Makefile` when compiling a new version of verovio with `make`.  It may be necessary to clear out the automatically generated cmake files and regenerate them.   I created a script called `verovio/tools/.configure` to do that:

```
rm -rf CMakeFiles CMakeCache.txt Makefile cmake_install.cmake
cmake ../cmake
```

So I often type `./.configure` in the tools directory after downloading a new version of verovio from github to avoid any problems with an old makefile.  This script was created after the build instructions were written, but perhaps useful to mention or integrate into the instructions, @lpugn? (I did not want to remember `cmake ../cmake` for example, or have to go to that documentation page a second time :-)

**Comment by lpugin** [comment]
Thanks. I added instructions here: https://github.com/rism-ch/verovio/wiki/Building-instructions#uninstall-a-previous-version

**Comment by craigsapp** [comment]
For the last step:

>Occasionally there are problems with updates necessary to the Makefile when compiling a new >version of verovio with make. It may be necessary to clear out the automatically generated cmake >files and regenerate them. To do that, run:

> rm -rf CMakeFiles CMakeCache.txt Makefile cmake_install.cmake

A person would also have to run `cmake ../cmake` as well, right?  Or are you assuming that they will know that from the instructions above about that step?

**Comment by apacha** [comment]
Thanks for the quick replies!

**Comment by lpugin** [comment]
> Or are you assuming that they will know that from the instructions above about that step?

Yes ;-)
