### ISSUE TITLE
Support for MXL (compressed MusicXML) import

### ISSUE THREAD

**Issue by samuelbradshaw** [rism-ch/verovio#2050]
MXL is a compressed container format for MusicXML. It would be great if it were possible for Verovio to render a score from MXL.

Some examples of MXL files can be found here:
https://www.musicxml.com/music-in-musicxml/example-set/

And a schema can be found here:
https://github.com/w3c/musicxml/blob/gh-pages/schema/container.dtd

**Comment by craigsapp** [comment]
MXL files are ZIP compressed files.  They could be uncompressed externally with unzipping programs or libraries, such as a random one I found on the web: https://gildas-lormeau.github.io/zip.js

But it would be interesting and convenient to have verovio unzip files internally.   This would also be useful for MEI files, perhaps.  One possibility could be with ZipLib:
     https://bitbucket.org/wbenny/ziplib/wiki/Home

Here is a simple test file:

[compressed.zip](https://github.com/rism-ch/verovio/files/5974949/compressed.zip)

(rename to compressed.mxl to get the original filename).

When unzipping an MXL file, there is a MusicXML which contains the contents of interest:

<img width="338" alt="Screen Shot 2021-02-12 at 5 32 39 PM" src="https://user-images.githubusercontent.com/3487289/107838162-5fb2c380-6d59-11eb-825b-bf0514bb7a65.png">

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work>
    <work-title>Title</work-title>
    </work>
  <identification>
    <creator type="composer">Composer</creator>
    <encoding>
      <software>MuseScore 3.6.0</software>
      <encoding-date>2021-02-12</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>6.99911</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1696.94</page-height>
      <page-width>1200.48</page-width>
      <page-margins type="even">
        <left-margin>85.7252</left-margin>
        <right-margin>85.7252</right-margin>
        <top-margin>85.7252</top-margin>
        <bottom-margin>85.7252</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>85.7252</left-margin>
        <right-margin>85.7252</right-margin>
        <top-margin>85.7252</top-margin>
        <bottom-margin>85.7252</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="Edwin" font-size="10"/>
    <lyric-font font-family="Edwin" font-size="10"/>
    </defaults>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="304.16">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>50.00</left-margin>
            <right-margin>674.54</right-margin>
            </system-margins>
          <top-system-distance>70.00</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <note default-x="80.72" default-y="-15.00">
        <pitch>
          <step>C</step>
          <octave>5</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>whole</type>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
```

There is also a file called `META-INF/container.xml` which contains the official list of contents for the MXL file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<container>
  <rootfiles>
    <rootfile full-path="compressed.xml">
      </rootfile>
    </rootfiles>
  </container>
```

Where `rootfile` is the file of interest (there could also be images or other multi media, although I have not see examples of that).

**Comment by lpugin** [comment]
We should probably go for a very lightweight library if we want to have this. https://bitbucket.org/wbenny/ziplib/wiki/Home is good but more than what we need in my opinion. Looking briefly at it it seems this could do the job
https://github.com/NicoG60/miniz-cpp

It is poorly documented but looks like it does everything we need. Everything is wrapped into one single header file https://github.com/NicoG60/miniz-cpp/blob/master/zip_file.hpp

In Verovio, we can add a `Toolkit::LoadZipFile` and a `Toolkit::IsZip` methods similar to `Toolkit::LoadUTF16File` and `Toolkit::IsUTF16`. It would be called from Toolkit::LoadFile in a similar way. 

The only thing that remains unclear to me is how to know the filename and path of the MusicXML file in the archive, but I think it would be easy for people who now the format to figure out what to do.

@samuelbradshaw are you willing to make a PR for this?

**Comment by craigsapp** [comment]
> The only thing that remains unclear to me is how to know the filename and path of the MusicXML file in the archive,

I would recommend not supporting anything other than the basic single-file MusicXML MXL file, since loading MXL files containing extraneous materials (such as PDF files in the example `contents.xml` file below) is not productive in a memory-limited situation such as a web-browser and should be discouraged.  The basic MXL file contains one directory with the index file (`META-INF/container.xml`) and one MusicXML file at the base of the zip (i.e., without a directory path), with the extension `.xml`. 

So in the basic case, you could search for the first (and presumably only) file in the zip archive other than META-INF/container.xml.   A more advanced implementation would search `META-INF/container.xml` for the first `.xml` entry, which should be the filename of the MusicXML file.

Also, it would probably be useful to allow an even simpler but more general case: allow any input zip file beyond MXL containers.  If a zip file is being imported and there is only a single file within it (or if there is no `META-INF/container.xml` index file), uncompress that file and then parse that file as usual (input format controlled by the verovio `--from` option).  Thus, if a single MEI file is stored in a ZIP file (perhaps disallowing multiple files in the zip to prevent bloating), that file would be expanded and processed in a similar manner as the MusicXML file within an MXL container.


------------------------

In the MXL file, there is always a file called `META-INF/container.xml` which lists the contents of the zip archive.   Here is documentation about it:

https://www.musicxml.com/tutorial/compressed-mxl-files/zip-archive-structure

Here is an example `META-INF/container.xml` file that shows the possibility of having more than one file in the zip file:

```xml
<?xml version="1.0" encoding="UTF-8">
<container>
  <rootfiles>
    <rootfile full-path="Dichterliebe01.xml"
              media-type="application/vnd.recordare.musicxml+xml"/>
    <rootfile full-path="Dichterliebe01.pdf"
              media-type="application/pdf"/>
  </rootfiles>
</container>
```

Compare to MuseScore's current `META-INF/container.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<container>
  <rootfiles>
    <rootfile full-path="Dichterliebe01.xml">
      </rootfile>
    </rootfiles>
  </container>
```


And here is Sibelius's `META-INF/container.xml` file:

```xml
<?xml version="1.0" encoding='UTF-8' standalone='no' ?>

<container>
 <rootfiles>
  <rootfile full-path="Dichterliebe01.xml" />
 </rootfiles>
</container>
```

Note that recent versions of MuseScore and Sibelius do not use `@media-type="application/vnd.recordare.musicxml+xml"`,
so probably assume that the first file ending in `.xml` in `rootfiles` is the MusicXML file to load.

**Comment by samuelbradshaw** [comment]
> @samuelbradshaw are you willing to make a PR for this?

I don't know how to run a C++ project locally, or add a third-party library as a dependency – unfortunately, most of my experience (which itself is limited) is in Python and JavaScript. I'm sorry I'm not much help. :(

**Comment by lpugin** [comment]
@samuelbradshaw no problem. Looking at it meant basically implementing it since it appeared to be fairly simple. I have it running locally and will push it once I cleaned things up. For the JS toolkit, the file will have to be passed as base64 encoded string, which I assume should be no problem.
