### ISSUE TITLE
pae editor 

### ISSUE THREAD

**Issue by musicus** [rism-ch/verovio#2052]
On the https://www.verovio.org/pae-editor.xhtml page, when entering the octatonic scale (OCT<sub>0,1</sub>), natural signs are not automatically inserted after a chromatically altered note in the rendered SVG (Safari 14.0), e.g: E following Eb does not carry a cancelling natural sign, although the Plaine & Easie Code in the textfield is correct.

![missing-accidental-in-SVG](https://user-images.githubusercontent.com/1203470/107985564-8c4c2280-6f87-11eb-8fe1-7fefeb9d8ea8.png)

**Comment by lpugin** [comment]
Plain and Easy is meant to be a purely visual encoding. I understand that it is confusing and looks wrong from a certain point of view, but it is how it is supposed to work. If you want a `natural` sign, unfortunately you need it to add it in the text field since these are not available in the piano keyboard

(You will notice, however, that verovio adds the `accid.ges="f"` for the second E in the MEI output when no natural sign is given.)

**Comment by musicus** [comment]
Ok. Got it.

**Comment by rettinghaus** [comment]
perhaps we could use parts of the editor from https://incipitsearch.adwmainz.net which implements naturals.
