### ISSUE TITLE
8va mark not aligned to notehead

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#207]
As seen in the corresponding commits from @craigsapp the 8va is not aligned to startid note but too far to the left.

**Comment by lpugin** [comment]
This is looking good to me.

![image](https://cloud.githubusercontent.com/assets/689412/18304747/72dbc4b0-74e4-11e6-9e06-99be3143bb22.png)

**Comment by craigsapp** [comment]
A problem I notice is that the right side of the 8va ending is centered on the last notehead; but it should be right-side aligned to the ending note.

**Comment by lpugin** [comment]
Yes, I just noticed it.

**Comment by lpugin** [comment]
Improved here 100c4d2637eb075cdc1b7c37e1f6d82d6e09b390

**Comment by craigsapp** [comment]
The update looks good:

![screen shot 2016-09-07 at 11 30 42 am](https://cloud.githubusercontent.com/assets/3487289/18306974/8f605628-74ee-11e6-9225-088a979bfa0e.png)

Here is an original:

![screen shot 2016-09-07 at 11 35 18 am](https://cloud.githubusercontent.com/assets/3487289/18307111/3c7029ec-74ef-11e6-83ae-4368039d09fc.png)

For future consideration, notice that the vertical terminating line is not ideal, since it ends with a fractional dash:

![screen shot 2016-09-07 at 11 36 57 am](https://cloud.githubusercontent.com/assets/3487289/18307173/804dc35e-74ef-11e6-87eb-cba87be09140.png)

There are lots of different styles that could be done, but the fractional dash style is not so great since it leave a little mark which is visually confusing (e.g., is it part of the 8va mark, or is it a separate symbol?)  The gap is the same vertically and horizontally, but perceptually the vertical gaps seems larger.

Also a stylistic thing is that the "8" is right justified with the left side of the note head in the original example.  This will be different in various editions, and I don't have a problem reading the 8va mark with the current layout in verovio (left justifying to the left side of the note, which is what Klaus was probably commenting on).

**Comment by lpugin** [comment]
Improved further ;-) db4893aacfc6fd99786fc4a9c7b4fcbd6cde8049

**Comment by craigsapp** [comment]
That looks great :-)

![screen shot 2016-09-07 at 12 26 17 pm](https://cloud.githubusercontent.com/assets/3487289/18308788/586a75f6-74f6-11e6-8d05-4e74042456d5.png)



Here is a survey of the ottava mark for the original example (Chopin Etude in F minor, Op. 10, No. 9):

http://imslp.org/wiki/Etudes,_Op.10_(Chopin,_Fr%C3%A9d%C3%A9ric)

Scholtz/C.F. Peters, c. 1900:

![screen shot 2016-09-07 at 11 56 54 am](https://cloud.githubusercontent.com/assets/3487289/18307796/38c58938-74f2-11e6-8150-e8db21ec9ad6.png)

Reinecke (Breitkopf & Härtel), c. 1879:

![screen shot 2016-09-07 at 12 00 28 pm](https://cloud.githubusercontent.com/assets/3487289/18307921/b17f16aa-74f2-11e6-9e07-32476df085ac.png)


Klindworth, Bote & Bock, c. 1880:

![screen shot 2016-09-07 at 12 01 45 pm](https://cloud.githubusercontent.com/assets/3487289/18307962/e1ec12ca-74f2-11e6-9e0a-14a0e338820a.png)

Rudorff, Breitkopf & Härtel), c. 1880:

![screen shot 2016-09-07 at 12 03 57 pm](https://cloud.githubusercontent.com/assets/3487289/18308072/4c5d53d0-74f3-11e6-9830-059af6176281.png)

 von Bülow, Aibl, c. 1880:

![screen shot 2016-09-07 at 12 06 57 pm](https://cloud.githubusercontent.com/assets/3487289/18308148/9bdf990e-74f3-11e6-987d-8f65a362360b.png)

Kullak, Schlesinger'sche Buch-und Musikhandlung, 1883:

![screen shot 2016-09-07 at 12 09 32 pm](https://cloud.githubusercontent.com/assets/3487289/18308229/f83f3984-74f3-11e6-8e66-4638fd569383.png)

Mikuli,  G. Schirmer, 1895:

![screen shot 2016-09-07 at 12 11 12 pm](https://cloud.githubusercontent.com/assets/3487289/18308283/31255e18-74f4-11e6-96ef-27e6419a2b94.png)

Friedman, Breitkopf und Härtel, 1913:

![screen shot 2016-09-07 at 12 17 55 pm](https://cloud.githubusercontent.com/assets/3487289/18308525/2f565348-74f5-11e6-9d5e-8e70abe0d134.png)

Cortot, Senart, 1915:

![screen shot 2016-09-07 at 12 20 12 pm](https://cloud.githubusercontent.com/assets/3487289/18308587/71f290b8-74f5-11e6-9e5d-f7371854bfc9.png)

Friedheim, Schirmer, 1916:

![screen shot 2016-09-07 at 12 22 04 pm](https://cloud.githubusercontent.com/assets/3487289/18308643/b56e0cd2-74f5-11e6-809f-0c5a455568fe.png)

Moscow: Muzyka, c. 1967:

![screen shot 2016-09-07 at 12 24 07 pm](https://cloud.githubusercontent.com/assets/3487289/18308714/ff632ad4-74f5-11e6-918d-cefb2a4f3219.png)

Pachmann, Augener, 1934:

![screen shot 2016-09-07 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/3487289/18308879/c3fc382c-74f6-11e6-97f9-ea6df4971489.png)

**Comment by rettinghaus** [comment]
Nice! As seen on the examples it would be nice to have the `@lform` working on `<octave>`. At least for values 'dashed' (default), 'dotted', and 'solid' that shouldn't be too hard.

**Comment by rettinghaus** [comment]
@craigsapp do you have an example for system breaks? As far as I'm aware, the ottava line usually juts out the staff a bit ...

**Comment by lpugin** [comment]
Great example set

**Comment by craigsapp** [comment]
Here are some examples of system breaks interacting with ottava marks.  Overall with this small sample, the rule seems to be to align the end with the barline.  This is for Beethoven piano sonata No. 23 in F minor, Op. 57, ("_appassionata_") (mostly extracted from IMSLP scanned editions):

Dukas, Durand, 1914:

The 8va line is flush or nearly flush with the barline:

![screen shot 2016-09-08 at 9 54 18 am](https://cloud.githubusercontent.com/assets/3487289/18341703/83249870-75ab-11e6-9a9c-c82bcbb6d544.png)

von Bülow, Oliver Ditson, 1876/Cotta,Stuttgart, 1872:

The 8va line ends before the barline (probably because another dash will not fit before the barline):

![screen shot 2016-09-08 at 10 11 11 am](https://cloud.githubusercontent.com/assets/3487289/18341961/e55106d6-75ac-11e6-8d39-33f0dc1ff6c7.png)

Ludwig van Beethovens Werke, S. 16, Breitkopf und Härtel, 1862-90:

Two before, one on, and one after the barline:

![screen shot 2016-09-08 at 10 16 38 am](https://cloud.githubusercontent.com/assets/3487289/18342176/c31bb54c-75ad-11e6-8887-a739ae12fe85.png)
