### ISSUE TITLE
Default input type

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#221]
The default input type for verovio has changed from PAE to MEI?

If so, the comment on line 171 of main.cpp should be updated:

https://github.com/rism-ch/verovio/blob/master/tools/main.cpp#L171-L172

```cpp
    // read pae by default
    type = MEI;
````

And the -h output should be adjusted on line 79:

https://github.com/rism-ch/verovio/blob/master/tools/main.cpp#L79

to say "(default is mei)".

**Comment by lpugin** [comment]
The comment indeed needs to be updated

**Comment by craigsapp** [comment]
I could do it :-)  Just making an observation of a default behavior change...  In any case, maybe this week I will implement the auto-detect functionality previously discussed, so that if `-f type` is not given, it auto-detects the input format (that would change the default behavior yet again).

Do I have to be prepared for UTF-16 XML files being input?  UTF-32?

For string input it will be easy to peek at the contents to do auto-detecting.

For regular file input, I can open them temporarily to look at them and then close them to send off to the importer to re-open them, but for standard input it may be more complicated.  Standard input can probably only be read once.  You are calling it "-", but maybe that is a dummy name?  If so, then there will not be a problem if I can peek into std::cin.

**Comment by lpugin** [comment]
> I could do it :-)

Thanks ;-)

> Do I have to be prepared for UTF-16 XML files being input? UTF-32?


As you have probably noticed only UTF-16 is handled for now. This was added because SibMEI writes UTF-16. I don't think we need UTF-32 now unless you need it. It will not change the entire flow if we want to add it eventually.

> standard input it may be more complicated

Yes indeed. We could restrict it to UTF-8 only. However, this will not solve the issue that it needs to be read twice for the auto detect. In any case it would be best not to have to write it to a temporary file somewhere since this always causes some platform specific issues.

If we want to allow UTF-16 with standard input the the best would be to remove the LoadUTF16File and to move the UTF16 to UTF8 conversion into LoadString (in it or into a LoadUTF16String).

Can you do that too ;-) ?

**Comment by craigsapp** [comment]
> If we want to allow UTF-16 with standard input then the best would be to remove the LoadUTF16File and to move the UTF16 to UTF8 conversion into LoadString (in it or into a LoadUTF16String).

> Can you do that too ;-) ?

That seems like a job for @ahankinson  :-), but if he sends me a sample UTF-16 file for testing, I can do it.  I used to have Sibelius on my computer until I got the hard disk replaced last year...

**Comment by lpugin** [comment]
Added here https://github.com/craigsapp/verovio/commit/2814ad0fd5336a8c652d13193b82b133f89c7b05
