### ISSUE TITLE
dir="bounce" on pedal should show a star

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#279]
When using `<pedal dir="bounce">` it sould look like 
![verovio ped1](https://cloud.githubusercontent.com/assets/7693447/17856327/43479ab2-687d-11e6-84d6-91302355fc07.png)

but only looks like
![verovio ped2](https://cloud.githubusercontent.com/assets/7693447/17856193/9460a066-687c-11e6-90f4-0954c4d57e58.png)

The code:

``` xml
<measure n="2" xml:id="d4
14233e371">
    <staff n="1">
        <layer n="1">
            <rest xml:id="d414233e373" dur="8"/>
            <beam>
                <note xml:id="d414233e381" pname="c" oct="5" dur="8" stem.dir="down">
                    <artic artic="stacc" place="above"/>
                </note>
                <note xml:id="d414233e400" pname="d" oct="5" dur="8" stem.dir="down" accid.ges="f">
                    <artic artic="stacc" place="above"/>
                </note>
            </beam>
            <beam>
                <note xml:id="d414233e421" pname="c" oct="5" dur="8" stem.dir="down">
                    <artic artic="stacc" place="above"/>
                </note>
                <note xml:id="d414233e445" pname="a" oct="5" dur="8" stem.dir="down" accid.ges="f">
                    <artic artic="stacc" place="above"/>
                </note>
                <note xml:id="d414233e466" pname="g" oct="5" dur="8" stem.dir="down">
                    <artic artic="stacc" place="above"/>
                </note>
            </beam>
        </layer>
    </staff>
    <staff n="2">
        <layer n="1">
            <beam>
                <note xml:id="d414233e486" pname="f" oct="2" dur="16" stem.dir="down"/>
                <note xml:id="d414233e504" pname="c" oct="3" dur="16" stem.dir="down"/>
                <note xml:id="d414233e522" pname="c" oct="4" dur="16" stem.dir="down"/>
                <note xml:id="d414233e540" pname="c" oct="3" dur="16" stem.dir="down"/>
                <note xml:id="d414233e558" pname="b" oct="3" dur="16" stem.dir="down" accid.ges="f"/>
                <note xml:id="d414233e578" pname="c" oct="3" dur="16" stem.dir="down"/>
            </beam>
            <beam>
                <note xml:id="d414233e596" pname="f" oct="2" dur="16" stem.dir="down"/>
                <note xml:id="d414233e614" pname="c" oct="3" dur="16" stem.dir="down"/>
                <note xml:id="d414233e632" pname="a" oct="3" dur="16" stem.dir="down" accid.ges="f"/>
                <note xml:id="d414233e652" pname="c" oct="3" dur="16" stem.dir="down"/>
                <note xml:id="d414233e670" pname="b" oct="3" dur="16" stem.dir="down" accid.ges="f"/>
                <note xml:id="d414233e691" pname="c" oct="3" dur="16" stem.dir="down"/>
            </beam>
        </layer>
    </staff>
    <dir staff="1" place="below" tstamp="1">cresc.</dir>
    <hairpin form="cres" staff="1" tstamp="3" place="below" tstamp2="6.5"/>
    <slur startid="#d414233e381" endid="#d414233e1055" curvedir="above"/>
    <pedal dir="down" staff="2" tstamp="1"/>
    <pedal dir="bounce" staff="2" tstamp="4"/>
</measure>
```

**Comment by craigsapp** [comment]
```xml
    <pedal dir="bounce" staff="2" tstamp="4"/>
```
Would result in the two symbols being rendered (when using in old-style pedaling)?:

![screen shot 2016-08-22 at 3 47 40 pm](https://cloud.githubusercontent.com/assets/3487289/17856906/fca150dc-687f-11e6-9705-4c936f886eeb.png)

That would be handy, but I can imagine complications related to implementing:

How would it be handled graphically across system breaks and barlines:

![screen shot 2016-08-22 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/3487289/17857149/f08426ca-6880-11e6-95f4-db6e4dd94b52.png)

**Comment by rettinghaus** [comment]
If I understand this correctly it is basically *one* symbol, other than in your scan @craigsapp 
So it should be rather easy to accomplish. Align the "Ped" and print a star in front of it.  

This is what lilypond would make out of it: 

![test-page1](https://cloud.githubusercontent.com/assets/7693447/17920928/91d78790-69d7-11e6-8f8c-12f70cfbc813.png)

**Comment by lpugin** [comment]
How would a bounce be represented with lines when occurring at the end of a system? Does anybody have an example?

**Comment by craigsapp** [comment]
This is Etude  Op. 10, No. 9 by Chopin.

Most of the editions put the pedal up aligned with the last 16th note of each beat.  And if encoded as a bounce, then the old style Ped/* notation would put the pedal up on the previous system and the pedal down at the start of the next system.

In a modern pedal line, the bounce at a system break should probably also be split across the break as well: The up-line would be at the end of the measure at the last system (at the barline), and the down line would be at beat 1 of the next measure.

Notice that there is more space between the */Ped when it is across the barline in these editions found in IMSLP, probablyl because all of these editions put the pedal-up on the last note, so not really encoding as a bounce.

http://imslp.org/wiki/Etudes,_Op.10_(Chopin,_Fr%C3%A9d%C3%A9ric)

http://ks.imslp.info/files/imglnks/usimg/5/59/IMSLP60294-PMLP01969-Chopin_Etudes_Schirmer_Mikuli_Op_10_filter.pdf

<img width="1151" alt="screen shot 2018-02-26 at 6 46 40 am" src="https://user-images.githubusercontent.com/3487289/36676485-ac8f4ece-1ac0-11e8-8955-b5a91a4f4945.png">

The first pedal up in measure 4 is interesting: it is one 16th note before the rest of the pedal-ups in its beat position...

http://ks.imslp.info/files/imglnks/usimg/f/fb/IMSLP113278-PMLP01969-FChopin_Etudes,_Op.10_BH2.pdf

<img width="858" alt="screen shot 2018-02-26 at 6 49 54 am" src="https://user-images.githubusercontent.com/3487289/36676607-f6546d14-1ac0-11e8-8748-d7782ba5a1f0.png">

http://ks.imslp.info/files/imglnks/usimg/5/5e/IMSLP112344-PMLP01969-kPiynd.pdf

<img width="997" alt="screen shot 2018-02-26 at 6 52 24 am" src="https://user-images.githubusercontent.com/3487289/36676721-4fd7863c-1ac1-11e8-8457-cfb48ae8393e.png">

http://ks.imslp.info/files/imglnks/usimg/9/95/IMSLP105539-PMLP01969-CHOPIN_Etudes_op._10_Ignaz_FRIEDMAN_Charles_FISCHER_1913.pdf

<img width="818" alt="screen shot 2018-02-26 at 6 53 32 am" src="https://user-images.githubusercontent.com/3487289/36676802-7aafb06e-1ac1-11e8-8e05-09eb1b2b9ef0.png">

http://ks.imslp.info/files/imglnks/usimg/7/71/IMSLP367492-PMLP01969-Chopin_Etudes_op.10_-_Cortot_(french).pdf

<img width="1031" alt="screen shot 2018-02-26 at 6 55 50 am" src="https://user-images.githubusercontent.com/3487289/36676947-d1059f14-1ac1-11e8-8a99-5444048a65cb.png">

The above is interesting since the pedalling cannot be viewed as a bounce (the pedal up is one 16th note before the next beat, and also interesting is that the pedal up is dropped where other editions start the simile/segue.

http://ks.imslp.info/files/imglnks/usimg/f/f3/IMSLP86562-PMLP01969-Chopin-Op10Friedheim.pdf

<img width="817" alt="screen shot 2018-02-26 at 6 58 18 am" src="https://user-images.githubusercontent.com/3487289/36677074-22499f56-1ac2-11e8-8503-52edb4fa7a98.png">

This is closer to a bounce concept as there is only a pedal down (implying that there must immediately be a pedal up just before it).

http://ks.imslp.info/files/imglnks/usimg/3/3d/IMSLP86296-PMLP01969-chopin-et-op.10.pdf

<img width="700" alt="screen shot 2018-02-26 at 7 00 32 am" src="https://user-images.githubusercontent.com/3487289/36677199-71d578ec-1ac2-11e8-97e4-835b50e27a17.png">

http://imslp.eu/files/imglnks/euimg/8/84/IMSLP239719-PMLP01969-Chopin_-_Etude_n%C2%B09_op10_.pdf

<img width="760" alt="screen shot 2018-02-26 at 7 01 47 am" src="https://user-images.githubusercontent.com/3487289/36677284-a004a1de-1ac2-11e8-95c8-24d37b663f3d.png">
