### ISSUE TITLE
implement instrDef element

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#283]
Verovio currently does not have an `instrDef` class.  This can be a sub-element of `staffDef` or `staffGrp`.  It would be handy to add this class to allow General MIDI instruments and MIDI channels to be specified in MEI data.

Example:

``` xml
    <staffDef>
         <instrDef midi.channel="14" midi.instrnum="0" midi.instrname="Piano">
     </staffDef>
```

@pe-ro: should `@midi.instrnum` and `@midi.instrname` be allowed at the same time?  They are redundant (in theory).  What should happen if they disagree?

I am wondering about (or will be wondering about) the `enum data_MIDINAMES` in `libmei/atttypes.h`.  This is a list of MIDI instruments, but also includes the drum-track instruments names after the list of General MIDI instruments.  I am presuming that the `@midi.instrnum` does not map to this enumeration (at least for the percussion instruments).  Also `@midi.instrnum` is supposed to be in the range from 0–127, but they are enumerated in the list from 1–128, which may cause confusion that this enumeration maps directly to `@midi.instrnum`.

**Comment by pe-ro** [comment]
I'm planning to add a Schematron rule that disallows simultaneous use of `@instrname` and `@instrnum`.

Perhaps I shouldn't be concerned, but non-GM MIDI troubles me.  It's tempting to allow `@instrname` to have non-GM values ("myInstrument", for example), but then there might be a need to map the user-supplied name to a GM instrument number, leading us right back to the simultaneous use of `@instrname` and `@instrnum`.  It appears that the way around this is say that `@label` should be used for non-GM instrument names, in which case `@instrnum` can supply the GM mapping.

**Comment by craigsapp** [comment]
How should the case of a sackbut be handled?   I suppose the `@instrname` and `@instrnum` are only for General MIDI values, but where would the indication that the instrument is a sackbut go?  In theory that could be `@instrname="sackbut" @instrnum="58"`, 58 being the GM instrument (offset from 1) for a trombone.  An algorithm for determining the MIDI instrument number could be:

(1) Search for `@instrnum`.  If found, then use.
(2) If not found, then search for `@instrname`.  If found and recognized, then use default mapping to GM Instrument number.
(3) If unknown `@instrname` then ignore.

Here is another possible cases.  For the Josquin Research Project, all parts are for voices, but when preparing MP3s via MIDI files, the vocal timbres are not used because they are so bad in most MIDI sequencers.  Instead I use different instruments for each vocal range, such as bassoon for soprano and bass, oboe for alto and clarinet for tenor.   This is done programmatically, as I don't store the MIDI instrument numbers in the data files.

**Comment by pe-ro** [comment]
First, let me retract what I said yesterday about using `@label` to hold a non-GM instrument name.  That violates the principle of not using a generic attribute for a specific purpose.  Mea culpa.

Second, your suggestion for determining the MIDI instrument number is basically sound.  However, given that the current values for `@midi.instrname` is a closed list, there can never be an "unknown" value.  This makes `@midi.instrnum` and `@midi.instrname` redundant, but it's a useful redundancy; that is, one can specify a GM sound using either one.  But, this means we need a Schematron rule that disallows using both attributes simultaneously.

To specify a non-GM sound, rather than use `@label`, as I suggested earlier, it would be better to add another attribute, say `@midi.patchname` ("_patch_" being the pre-GM term for a sound configuration) that can hold a name (a NMTOKEN, actually), for instance "_awfulClyde_", but not "_awful Clyde_".  A non-GM patch can be mapped to a GM instrument by adding `@midi.instrnum` or `@midi.instrname`, but again, not both.

A word of caution -- `@midi.instrname` and `@midi.patchname` exist to map an instrument named in the score to a MIDI instrument (GM)  or patch name (non-GM).  Their values may or may not be the same as the "score instrument", to use MusicXML terminology.  For example, the score may say staff 3 is for "alto" or "sackbut" (captured in either `staffDef/@label`, `staffDef/@label.abbr` or `staffDef/label`).  If GM is in use, `@midi.instrname` may contain "Voice_Oohs" or "Synth_Voice" or even "bassoon".  Or `@midi.instrnum` may hold a GM instrument number.  When GM is *not* in use, then one must use `@midi.patchname` to map the "score instrument" to MIDI.  In this case, the name will be a local one; that is, whatever name is used by the user's MIDI gear, for example "hardart" or even "sackbut", if there's a patch with that name.

**Comment by lpugin** [comment]
General feature request

**Comment by lpugin** [comment]
Implemented https://github.com/rism-ch/verovio/pull/793

**Comment by rettinghaus** [comment]
However `@midi.instrname` is not supported. Question is still how to deal with that correctly. Should we have a map from `@instrname`to `@instrnum` in `LibMEI`? But then, which one should be preferred?

**Comment by lpugin** [comment]
I am not sure we need a mapping in LibMEI because `data_MIDINAMES` is already providing a 1-based list, but maybe I am overlooking something. I have no particular opinion on which one to prefer.
