### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by marie-ototoi** [rism-ch/verovio#323]
Hi Laurent, 
You asked how I would see this overview I had the feeling was missing, here is a try. 
Is the interpretation correct ? and do you think it could be helpful ? 
(if so I could add it to gh-pages, this is only a screenshot)
Best regards,
Marie
![overview_20161003](https://cloud.githubusercontent.com/assets/1785024/19042772/a1f53a66-898d-11e6-9c50-3b5b6f31e635.png)

**Comment by lpugin** [comment]
Hi Marie,
many thanks for this. This type of help is highly appreciated. A few comments.

Verovio isn't really a set of libraries, I think we can say that it is one library. 

Then, I would say that "Verovio is a C++ codebase that can be integrated into various environments. The C++ Python, Java toolkits are ...

Finally, I am less sure about the last example with the server-side and client-side integration. It looks that the JS toolkit can interact with SVG generated from the server, which is not really the case. One we might want to show here is that in some cases we can have server side processing on the MEI before it is processed by Verovio (server-side or client-side, probably client-side). This can for example be XSLT. What do you think? Other ideas?

I created a gh-pages-develop branch, feel free to make a pull request there (including the source files of the illustrations). I will actually leave this branch since it will be useful for people to make such proposals in the future.

**Comment by marie-ototoi** [comment]
Bonjour Laurent,

Thank you for your feedback and clarification... will try again in the new branch !

A few questions to try and get the whole picture...

Do I understand correctly that people cannot install python or command line compiled versions without  building them themselves from C++ ?
So the audience would be : 
- javascript developers who need to display MEI documents (+ midi output)
- C++ developers who want to set a workflow for treatment and display of MEI files
Do you have an idea of the proportion ?
Can you think of other cases ?

DARMS format is mentioned on the command-line.xhtml page, but not in the Other Formats section, whereas Humdrum is only in the Other Formats... is there any difference in formats handled by one or the other version or is it just the doc that has to be fixed ?

I'm asking all this because I think it would be nice if the user can understand quickly if the lib is the right tool according to his needs (treating and/or displaying and/or "listening" from the score), constraints (formats, infrastructure) and skills (languages mastered)

++++

**Comment by lpugin** [comment]
> Do I understand correctly that people cannot install python or command line compiled versions without building them themselves from C++ ?

This is correct. Providing binaries would be over the top I think. However, building the python or the java toolkit is pretty straightforward. The only requirement is a compiler and swig. So the toolkit needs to be built but there is not really C++ involved in the process.

> * javascript developers who need to display MEI documents (+ midi output)
* C++ developers who want to set a workflow for treatment and display of MEI files Do you have an idea of the proportion ? Can you think of other cases ?

Not really C++ developers only as explained about. The python and java bindings are precisely there for developers who work in these environment.

You are right that things are somehow scattered. The building instruction for the python toolkit are provided there
https://github.com/rism-ch/verovio/wiki/Building-instructions , which is referred from the website page http://localhost:4000/python.xhtml
The wiki is quite handy for this type of documentation, so I am not sure what is best between explaining this better (with the structure you propose) or move the wiki (back) to the gh-pages. I would personally prefer to keep the wiki, and maybe making more use of it.

DARMS / humdurm: we could actually remove the darms input because it is too basic and not used as far as I know. We should definitely add humdrum, which is new.

**Comment by craigsapp** [comment]
> Do I understand correctly that people cannot install python or command line compiled versions without building them themselves from C++ ?

That seems true to me.  Google Code had a more convenient system for providing compiled code.  But it is also possible in GitHub if that is of interest:

https://help.github.com/articles/about-releases

https://help.github.com/articles/creating-releases

https://github.com/blog/1302-goodbye-uploads

https://github.com/blog/1547-release-your-software

>So the audience would be:
* javascript developers who need to display MEI documents (+ midi output)
* C++ developers who want to set a workflow for treatment and display of MEI files Do you have an idea of the proportion ? Can you think of other cases ?

Just because binaries are not supplied does not mean that users cannot generate them themselves.  Command-line users of verovio do not have to write any code to use verovio, as the source code for the command-line interface is already provided.  Also, a command-line user does not need any specific knowledge of C++ in order to compile the code.   Most command-line users will know how to compile the code, especially in linux/unix (Windows users need a lot of help to compile, and OS X users need a little help).  The audience/function of verovio for the command-line would be similar to what you list above for javascript developers. 

The main point of verovio is that you can choose to work in javascript inside of a web browser, or you can run the equivalent verovio interface directly within the operating system such as from the command line, or equivalently from a python interface.  The command-line version will run faster and does not have problems with memory limits.  "Workflow" from the second point is more applicable to a command-line usage of verovio -- C++ developers could integrate the verovio library into their own interface, which would not be characterized as a workflow as it would be integrated directly into a compiled interface that would typically be a stand-alone graphic interface such as MuseScore/Finale/Sibelius.   A Frescobaldi (lilypond) style setup would involve the existing command-line interface in a workflow type arrangement.

> DARMS / humdurm: we could actually remove the darms input because it is too basic and not used as far as I know. We should definitely add humdrum, which is new.

The DARMS importer is a fairly basic implementation (and there are variants on DARMS which complicates things).  The Humdrum (or humdurm as I also tend to spell it :-), is a nearly generalized conversion, and I will work on final refinements over the next year or so.

A list of limitations or current states for the converters in/out of verovio would be useful to give somewhere.  For example MIDI output is limited to a single tempo (quarter note = 120 bpm) and ties are not recognized by the converter (tied notes are re-struck).  I am wondering about how transposing scores are also handled, but have not tested yet...

**Comment by lpugin** [comment]
@craigsapp for the MIDI output, there is there http://www.verovio.org/midi.xhtml information about was is taken into account and the future work for what it not. Transposing instruments work.

**Comment by marie-ototoi** [comment]
Ok then we would have something like : 
	•	javascript developers who need to display MEI documents (+ midi output) & deal with user interaction
	•	C++ developers (or developers comfortable with compiling C++) who want to set a workflow for treatment and display of MEI files (without user interaction)

Although I understand it is not a question for developers like you, I think a developer who has never done C++ does not necessarily know how to run a compiler... of course he could learn, but even if it’s not so complicated the probability he will is rather low, if the only thing it can bring him is to run a XSLT (in the case where he needs to deal with user interaction and cannot combine server and client treatment as I had first thought)… he will most probably find a python or node lib for this, because there’s no point in making the workflow + complicated when it brings too little.

Which is all perfectly fine, my point is only that it is so much more comfortable when you can figure all this out in a minute... 

I don't mean these categories should appear : they are just useful for us to think of the way information should be displayed (and to make sure I'm not going in a direction which is not the one you have in mind)

And I guess it's ok to have things in different places if the overview is clear and links to the right places

So now I will try to sum this up !

**Comment by lpugin** [comment]
OK, we can see once you have summarized it, but I am not fully convinced by the two categories. I would rather say:

1. The JavaScript toolkit (as you describe it)
2. The toolkit bound to programming environments (python or java)
3. The command-line toolkit
4. As a linked C++ library

For 1, the compiled version is provided. For 2 and 3, it needs to be compiled. 4 requires C++ knowledge, but this is the only case. This is indeed low level.

For two, it is quite basic and we can refer to this https://github.com/rism-ch/verovio/wiki/Building-instructions#building-the-python-toolkit

**Comment by craigsapp** [comment]
I like those 4 categories (other than #3 should be #1 :-)

For the building instructions page, It would be good to outline on that page how to setup the compiling process for the main operating systems.  For example, OS X users would have to install the xcode command-line tools or compile in XCode.  And cmake does not come with these tools, I think.  When I get my new laptop, I will make notes of what setup and installation I had to do in order to get verovio compiled.  Unix/Linux should mostly be able to figure out from the current instructions, but a page about how to compile with XCode and another for Microsoft Visual Studio would be also useful.

**Comment by craigsapp** [comment]
Regarding the emscripten building instructions on
   https://github.com/rism-ch/verovio/wiki/Building-instructions
there are three files created in the compiling process:

```
build/verovio-toolkit.js
build/verovio-toolkit.js.gz
build/verovio.js
```

What is the difference between verovio.js and verovio-toolkit.js?  Presumably verovio.js is compiled first and then further processed to generate verovio-toolkit.js.  Perhaps it should be automatically deleted if it is only an intermediary file? 

And for verovio-toolkit.js.gz, is that a necessary file?  If someone needs that file, they could compress it themselves.  I also checked the gh-pages webserver, and it automatically sends files in .gz format to the client browser if it accepts compressed files (without the need to store the .gz file on the server).  Not including them in the javascript folder in verovio/gh-page branch would keep down the long-term clutter and repository size for the gh-pages branch.

**Comment by craigsapp** [comment]
For the diagrams on the page:

https://cloud.githubusercontent.com/assets/1785024/19042772/a1f53a66-898d-11e6-9c50-3b5b6f31e635.png

I would recommend that the arrow from MEI input into verovio should be reversed so that it points to verovio (red circles), and then perhaps change "reads" to "read" or "input".  If using "input" then perhaps change "writes" to "output".

![screen shot 2016-10-05 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/3487289/19135665/355c20ce-8b1b-11e6-81f6-d371fe03f0ce.png)

For the text:

![screen shot 2016-10-05 at 4 53 26 pm](https://cloud.githubusercontent.com/assets/3487289/19135801/42b6014e-8b1c-11e6-8962-bcde50b99c52.png)

Have you tried loading it into Adobe Illustrator?  Here is what I get when loading verovio SVG output into Adobe Illustrator, Creative Suite 3 version:

![screen shot 2016-10-05 at 4 52 59 pm](https://cloud.githubusercontent.com/assets/3487289/19135811/591a6f06-8b1c-11e6-8a50-c7c2abd63d50.png)

[Inkscape](http://www.inkscape.org) is another possibility for reading.  It is not working currently on my computer (I will try re-installing).  I remember that it works slightly better than Adobe Illustrator at reading verovio SVG files, but I had to adjust the stroke widths after loading or something similar.

Related, I already have had people ask me how to load the SVG output from verovio into Microsoft Word, and it is quite difficult to do other than as a converted bitmap:

http://superuser.com/questions/397644/inserting-svg-files-in-a-microsoft-word-document

Regarding this, I will someday submit a feature request for verovio to output EPS file which can be dragged/dropped into Microsoft Word (unless new versions of M$ Word start to load SVG images without converting them to bitmaps).  SVG and EPS files would be nearly identical in their contents.

Note the typo `independant` which should be `independent`.

Repeating Laurent a bit for the last image, how does the user interaction work?  It would not be quite as interactive as the second diagram, since the graphic notation can be re-drawn within the browser rather than going back to the server. A "static layout/dynamic interaction" could be done with this configuration: the SVGs would be created on the server and then sent to the browser.  In the browser they could be manipulated with CSS to highlight notes, etc.  This is similar to how I use SVG images rendered with SCORE to do dynamic highlighting of a score along with a recorded performance playback:
     http://www.ccarh.org/haydn/op20n5/mvmt1
     http://www.ccarh.org/haydn/op20n5/mvmt2
     http://www.ccarh.org/haydn/op20n5/mvmt3
     http://www.ccarh.org/haydn/op20n5/mvmt4

And the javascript toolkit (yellow circle) should not be in the diagram since the SVG generation is handled by the red circle(s), unless you mean "JavaScript" rather than "JavaScript toolkit", which more implies the "javascript toolkit version of verovio".

![screen shot 2016-10-05 at 5 00 24 pm](https://cloud.githubusercontent.com/assets/3487289/19135945/70b91e9a-8b1d-11e6-90a0-09c7e182bf6c.png)

**Comment by lpugin** [comment]
Diagram: Verovio also writes MEI, so the arrow goes in both directions. Also, Command-line and C++ toolkit are the same, so we should have only Command-line. (in the JS version, and also in the Python and Java version, the toolkit acts as a controller that keeps the data in memory. In the command-line version, it is a one call action, so it is different usage)

Import: it works perfectly with Inksape. It can also be imported into Gimp or converted to other formats with Rsvg. (It seems that with some software the scale factor has to be 100% for this to work.)

Last case: I think Craig is right, we can have interaction with the SVG but this should be only JavasScript / CSS (and not the toolkit). Maybe you can use another color for that circle?

**Comment by craigsapp** [comment]
> Diagram: Verovio also writes MEI, so the arrow goes in both directions.

But probably for the overview you don't want to confuse with this level of detail; otherwise, you would also need to include multiple inputs formats, since MEI input to MEI output is a bit confusing (but could also be MEI score layout to MEI page layout).

**Comment by marie-ototoi** [comment]
Tried to integrate your feedback.
Think it might better to sum up Installation and compilation info in another page, with links to wiki, etc
