### ISSUE TITLE
Return status flag in JS version of toolkit

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#342]
It would be useful for the JavaScript version of the verovio toolkit to return a status flag (and other versions as well).

http://www.verovio.org/javascript.xhtml

For example `loadData()` might be a good place to return the status if there was something wrong with the input data.  It could also be tied somehow to `renderData()` or have a new function such as `getStatus()` which indicates that something was wrong.  It would probably be implemented as a variable in the Toolkit class which could be set to "good" when first loading data, and then set to "bad" during the processing of the loaded data.

Probably the status value would return "0" on success, and otherwise different status errors could be returned.

**Comment by ahankinson** [comment]
I can see how this would be useful, but what's the particular use case? Would it be better to implement this so that status codes are the same across all languages (JavaScript, Python, command-line)?

**Comment by craigsapp** [comment]
What do you mean?  The verovio Toolkit class exists in all language interfaces, so the status codes would be the same in all languages.

**Comment by lpugin** [comment]
I guess this relates to #180

**Comment by craigsapp** [comment]
Yes, similar to #180, but that is more about giving feedback to a human as to why there was an error.  The idea for this feature request is more low-level automated feedback to the software controlling verovio.  Mostly I am interested in a binary yes/no state for this, but merging #180 functionality into this would be a good extension.   Warning-level feedback is not interesting in my current use case, but I can imagine it may eventually be useful as well.

My use case is that I want the JavaScript interface that controls the verovio toolkit to understand if there were any error that prevented verovio from producing SVG output.  Specifically in VHV when I type data in the editor, it would be useful for there to be a warning that there is a problem with the data, and the SVG image currently being displayed is from the last correct state of the data that was sent to the toolkit and not from the current state of the data.  In this situation I want the JS interface to ask verovio if there was a problem, and if so, notify the user (in whatever way I would do that, such as change the background color of the page) of the problem.

Implementation would be something along the lines of a state variable stored in the Toolkit class.  This state would be initially set to "good" when starting `vrvToolkit.loadData()`, and at any point there was a fatal error preventing any SVG to be output, this state would be set to "bad".  The controlling program can later ask verovio what happened and then go on to inform the user about the problem.

**Comment by lpugin** [comment]
You seem to think binary ;-) If we do this we should straightaway make it match the log message we get. Something like INFO (good), WARNING, ERROR (bad). It would be to your application if you want to treat the warning level as good or as bad.

**Comment by craigsapp** [comment]
I want to know if verovio produced (or will be able to produce) an SVG image with the given input data, so I do only want one yes/know answer to the question "were/are you able to generate an SVG image?".  Anything more elaborate is ok, of course, as long as that question can be answered. I could probably look at the SVG output from `renderData()`, but that function could return an empty SVG file rather than an empty string.  Also, I probably want to know what the status is after running `loadData()` but before `renderData()`.

The current log messages are printed to the console, so I don't think JS has access to them.  Perhaps they can also be passed as a JavaScript object through a toolkit function:

```json
[
    {"type":"WARN", "message":"Some sort of warning message"},
    {"type":"INFO", "message":"Some sort of info message"},
    {"type":"INFO", "message":"Another sort of info message"},
    {"type":"ERROR", "message":"Some sort of problem which terminated processing of the data"}
]
```

I could then search for any `type:"ERROR"` messages in the list and alter the user (particularly the or last message if there is an error which should presumably terminate processing of the data).

This system might need the controlling program to clear the log in the toolkit, such as for reprocessing data, and/or `readData()` would automatically clear the previous list of log messages.

**Comment by craigsapp** [comment]
I see `getLog()` in the JS interface to verovio:

<img width="687" alt="screen shot 2016-10-31 at 18 29 00" src="https://cloud.githubusercontent.com/assets/3487289/19876974/2b6a61b6-9f98-11e6-8edf-d7735e177600.png">

Perhaps this is what I want?  I already had that in my JS code, but it never seems to return data (could be that annoying interaction with emscripten).  I will look in to that later...

**Comment by ahankinson** [comment]
> My use case is that I want the JavaScript interface that controls the verovio toolkit to understand if there were any error that prevented verovio from producing SVG output.

It seems to me that the trick will be determining whether there actually an error. If the error is on the input (i.e., the MEI/Humdrum you are asking it to render) then you will need a method to determine whether it is 'correct,' and the only real way to do that is to run an XML validator. At the very least you would need to check well-formedness, but a more comprehensive check would validate it against the spec. That would be a very expensive process.

If you're checking the output (does it produce SVG) then (other than the logging output of Verovio) you wouldn't really be able to point at what was actually wrong about the input you provided. Are you asking it to render a tag that it doesn't know about? Or are you putting a tag where it doesn't belong (a 'note' inside a 'measure,' for example). So in that sense, it could be argued that `renderData` should *always* return the `SUCCESS` case, since it was "successful" in rendering the data it was given--it's just that the data it was given was syntactically or semantically bad.

What I might suggest, if this is even possible, is that you define a listener function for different log levels. So when a particular condition (error, warning, info, debug) is logged, you have a function that takes that condition and the message and does something to it. Bonus points if you can redirect the output of the console if a handler function is specified, so that you can control the logging output of the toolkit at runtime.

So:

```
var tk = verovio.toolkit();
tk.error = function(message) { ... do something ... };
tk.warning = function (message) { ... do something ... };

tk.renderData('foo.mei'); 
```

(I didn't check the actual code before writing that, so you'll forgive me if I get the specifics wrong).

**Comment by lpugin** [comment]
@craigsapp : am not sure what is the status of GetLog(). You can change it and make it return a Json object as you are suggesting.

@ahankinson : I am not sure I fully get your proposal. We can talk about it.

**Comment by ahankinson** [comment]
Another way to put it that might be a bit more jQuery-esque:

```
tk.on('error', function (message) {
    console.log(message);
});
```

Defining an error handling function just means that only one function can handle the errors at a time. If you had an events system that emit messages like 'error' or 'warning,' though, you could listen for these events and subscribe a number of different functions to them.

**Comment by lpugin** [comment]
OK, we can sort this out together with #180
