### ISSUE TITLE
add iomidi

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#365]
Is there a reason why midi output is integrated into doc.cpp and no iomidi.cpp in existence?

**Comment by lpugin** [comment]
No particular reason. Actually no IO class other the MEI has an output. For MIDI the call is indeed in Doc with one method `Doc::ExportMIDI`. Most of it is happening in the functors GenerateMIDI. We could change this but I am not sure it would change much. Anything not clear in particular?

**Comment by rettinghaus** [comment]
I can think of at least three reasons to split it up:
1. Code structure – every input/output should have it's own class
2. to exclude it in the JavaScript toolkit (e.g. for Bach digital we don't
need it at the moment)
3. maybe someone has too much spare time and wants to implement a MIDI
input

**Comment by lpugin** [comment]
OK, I see your point. But the problem is that outputting uses functors which we cannot really isolate in a MIDIOutput class, so I will need to think about it.

If somebody wants to write an importer, then this should definitely be in its own class.

**Comment by craigsapp** [comment]
> No particular reason. Actually no IO class other the MEI has an output.

`iohumdrum.cpp` outputs MEI data . but really it does this by piggy-backing on verovio to create a pugixml-MEI structure directly in verovio and then lets `iomei.cpp` take care of the output ;-)

Someday I want to do an output from verovio to SCORE, so placing the code for that functionality into `ioscore.cpp` would be obvious (I don't know if it would require a class encapsulation).  SCORE output would be related to SVG output, but would also need awareness of the pugixml-MEI data structure. In theory I could do SCORE input, but that will take a lot more work and be a somewhat open-ended problem...

I haven't looked at SVG output yet.  Do you create a pugixml form of the SVG file(s) first and the convert text when outputting?  If so, then I would have a SCORE exporter doing something like this:
    `ScoreOutput::convert(pugixml& svgdata, pugixml& meidata);`
and multiple pages:
    `ScoreOutput::convert(vector<pugixml>& svgpages, pugixml& meidata);`
using whatever the data type is for each of them instead of "pugixml".

**Comment by lpugin** [comment]
The SVG in not directly an output but a rendering device context. But it do generate a pugixml tree. For now I don't think it accessible from outside the SVGDeviceContext class but of course we can change this.
