### ISSUE TITLE
Add data.DURATION.gestural.pat 

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#380]
By now `@dur.ges` only allows values from `data_DURATION` so there's no way to import midi ticks or seconds.

**Comment by lpugin** [comment]
Yes, this is a case where the attribute content allows alternate types
http://music-encoding.org/documentation/3.0.0/data.DURATION.gestural/

The LibMEI version used by Verovio generates data types based on the MEI schema and which were originally all handled as std:string. The problem is that for now it supports only one type per attribute (e.g., and integer, a string, or a data type). 

To change this we would need to modifiy LibMEI further. One option is to define something like an alternate data type class (AlternateDataType) that can support more than one type, and have the modified version of LibMEI generating the appropriate code for reading and writing attributes. This is not trivial. I guess it needs to contain and member for all the possible types. I am not sure how and where to define this. Alternatively, we could use C++ std::pair or std::tuple, but this would be about the same work to be done in LibMEI.

If you want to change this the place to look is the Verovio version of LibMEI and in particular this file
https://github.com/rism-ch/libmei/blob/master/tools/includes/vrv/config.yml

As you can see, data.DURATION.gestural is mapped to data_DURATION, which itself had to be defined directly in Verovio because this is a choice in MEI, another data type format that is not supported in the LibMEI code generation.
http://music-encoding.org/documentation/3.0.0/data.DURATION/

As you can see, this is quite complex and any suggestion how to handle this is welcome. The important point is to find the right balance between auto-generated code and code written by hand to maintain. The risk here is to have a lot of code to be written and maintain just to auto generate code for alternate data type. Maybe writing the code by hand for all MEI alternate data types will be easier.

**Comment by lpugin** [comment]
PS The other place to look at in LibMEI is here (the version for Verovio)
https://github.com/rism-ch/libmei/blob/master/tools/langs/cplusplus_vrv.py

One thing to think about is what to expect to be returned as type or class when then doing GetDurGet() in Verovio. The logic would be it to be an AlternateDataType, (or an std:tuple). Then we would need to check if it is a data.DURATION.gestural.prop, a data.DURATION.gestural.pat, or a data.DURATION.mensural type, and then eventually get its value.

**Comment by rettinghaus** [comment]
OK. As this is more of a LibMEI issue, should we move this over there? 
Looks like more work to be done here. I'll look into it but postpone it for now until after X-Mas.

**Comment by lpugin** [comment]
OK, I moved it there.

**Comment by lpugin** [comment]
PS There are currently 9 alternate data types in MEI, so I think that coding them by hand will be simpler even though it will be a shame not to benefit from LibMEI for these.
