### ISSUE TITLE
Equal width of all bars?

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#465]
Would it be possible for Verovio to make all bars/measure of equal width, regardless of how many notes they contain.

There is command ` --even-note-spacing ` but not sure what this is doing?

**Comment by lpugin** [comment]
`--even-note-spacing` does not take duration into account for spacing the notes. This is mostly useful for producing compact incipits, especially when they contain long durations. Having equal with bars does not make sense to me and I assume you have a very specific need here, don't you?

**Comment by craigsapp** [comment]
`--spacing-non-linear=1.0` is what you want (or close to it)

```
verovio --spacing-non-linear=1.0 --spacing-linear=0.05 input.mei
```

The `--spacing-linear=0.05` was used to contract the spacing (otherwise it was very wide).

Example:

<img width="526" alt="screen shot 2017-02-02 at 08 44 07" src="https://cloud.githubusercontent.com/assets/3487289/22558828/f97751de-e923-11e6-97f9-7ebfca4394ae.png">

Default layout (`--spacing-non-linear=0.65`):
  
<img width="860" alt="screen shot 2017-02-02 at 08 46 22" src="https://cloud.githubusercontent.com/assets/3487289/22558860/1bfa5f12-e924-11e6-8dfc-75a300d47ff9.png">

0.65 meaning that the space of a whole note is 0.65 that of two half notes, the space of a half note is 0.65 that of two quarter notes, and so on.  With 1.0, the spacings are proportional to the duration.  There could be some minor disturbances in the spacing related to barlines, and in tight situations things like accidentals will add exta space.

**Comment by craigsapp** [comment]
>  Having equal with bars does not make sense to me and I assume you have a very specific need here, don't you?

Having notation spaced proportional to time (`--spacing-non-linear=1.0`) is a common way of displaying notation in modern (academic) compositions, particularly in the New Complexity school:
     https://en.wikipedia.org/wiki/New_Complexity
Also common in computer and electro-acoustic music notation.

**Comment by lpugin** [comment]
Looks like it is possible, then.
