### ISSUE TITLE
Highlighting measures without knowing id in Javascript

### ISSUE THREAD

**Issue by timtrepie** [rism-ch/verovio#524]
Is it possible to get access to a specific measure with Javascript without knowing the ID of the element? 
I know the thing with :nth-child() or :eq(), but thats not, what I want. I want to have the possibility to highlight, for example, the fourth measure. With nth-child(4) I only get the 4th measure shown, but not the real 4th measure. If I have zoomed in and go to the next pages, every "4th measure" is highlighted. How can I prevent that?

http://www.verovio.org/tutorial.xhtml?id=topic03
So thats what I have, but not what I want: 
`$(".measure:eq(4) .staff").attr("fill","#000").attr("stroke","#000");`

**Comment by craigsapp** [comment]
The problem is that the `measure@n` attribute is not passed on to the SVG `g@class="measure"` elements.  Without that information, you have to look back at desired measure in the MEI data, and pull out the xml:id parameter to reference the specific measure in the SVG score.

<img width="1649" alt="screen shot 2017-03-18 at 11 24 21 am" src="https://cloud.githubusercontent.com/assets/3487289/24074842/c4f13e9e-0bcd-11e7-90c9-1767de5fe5f0.png">

One possibility would be to encode the measure number in the ID for the measure, and then you can use regular expressions in the selector to access the measure number.   For example, if the measure ID included the string `BAR4x`, then the CSS selector `*=`
```
g[class*="BAR4x"] 
```
The `x` is used to terminate the number; otherwise, measure 43 would also be highlighted...


-----------------------

Another way which is newly possible in the latest develop version of verovio is to place the measure number into the `measure@type` attribute.  The `@type` attribute contents will be appended to `@class` attributes in the SVG image.  The type tag cannot start with a number, so you should prefix it with `m` for "measure" (or `b` for "bar").  Below I am prefixing with `m-`:

<img width="1684" alt="screen shot 2017-03-18 at 11 53 32 am" src="https://cloud.githubusercontent.com/assets/3487289/24075086/3e728af8-0bd2-11e7-8190-cd3ed92f0f2d.png">

Notice that the fourth measure element is the third actual measure, since the first measure is an incomplete pickup bar.

Now you can highlight the fourth measure element instead as the 3rd real measure:

```
$("svg .measure.m-3").attr("fill", "#d00").attr("stroke", "#d00");
```

Resulting in:

<img width="1658" alt="screen shot 2017-03-18 at 11 55 27 am" src="https://cloud.githubusercontent.com/assets/3487289/24075132/e2d3da84-0bd2-11e7-83b5-861fd121f8c5.png">

**Comment by lpugin** [comment]
Hi Tim,

You can simply use the `getElementAttr` method and look at the value of the `@n` attribute. This means something like:

```
$(".measure").each(function(i) {
    var attr = vrvToolkit.getElementAttr($(this).attr("id"));
    if (attr.n && (attr.n == "4")) {
        $(this).attr("fill", "#f00").attr("stroke", "#f00");
    }
});
```

**Comment by craigsapp** [comment]
````
$(".measure").each(function(i) {
    var attr = vrvToolkit.getElementAttr($(this).attr("id"));
    if (attr.n && (attr.n == "4")) {
        $(this).attr("fill", "#f00").attr("stroke", "#f00");
    }
});
````

That would be good to add to the page  
      http://www.verovio.org/tutorial.xhtml?id=topic03

:-)

---------------------------

The algorithm is:

(1) generate a list of all the elements in the SVG which have class="measure".
(2) for each of these measure elements find the corresponding element in the MEI data with the matching id.

Step 1 is O(N), where N is the number of elements in the SVG image, generating a list of elements M long.
Step 2 is O(M*P/2) on average, where P is the number elements in the MEI data.

So the total computational complexity is O(N) + O(M*P/2), where approximately P >= N, and P could be much larger than N.  

Luckily M is typically 1, so not a real problem unless P is very large and the highlighting were done very often.

Question: does `vrvToolkit.getElementAttr()` look at all pages in the MEI file, and/or does it start by looking on the current page that was last extracted from it (or could a particular page number be specified to limit such a search)?  Probably not, but maybe adding a function such as vrvToolkit.getElementAttrOnCurrentPage() might be interesting.  That would set the computational complexity to O(N)+O(M*N/2), which is a good improvement for Symphonic sized MEI files.

If the measure numbers were embedded in the classes of elements in the SVG, then

```javascript
$("svg .measure.m-3").attr("fill", "#d00").attr("stroke", "#d00");
```

has a computational complexity of O(N) which is less than O(N) + O(M*P/2), but perhaps not interestingly so since M=1 usually.

But access to the vrvToolkit and the MEI source data may also not be available in certain software configurations (not in this one, though); for example, when pre-computing the SVG images on a server.  

Another thought: there can only be one vrvToolkit instance on a page at a time (probably due to emscripten static memory allocation -- how might WebAssembly change this?).   If there are more than two SVG images on a page from different MEI source files, then vrvToolkit has to be used more as a batch processor rather than interactively, disadvantaging the O(M*P/2) method, since you would have to keep track of which MEI files is inside the vrvToolkit.

So I am thinking it would be nice to have a verovio option for embedding the measure number to the SVG image (related to the next message I will respond to :-)

**Comment by lpugin** [comment]
It is already in the tutorial.
http://www.verovio.org/tutorial.xhtml?id=topic05

**Comment by craigsapp** [comment]
I have to read through the whole tutorial? And that page is about pitch, not measures :-) A fun thing would be to allow digit keys to highlight measure@n (0-9 at least) on the demo for that page.
