### ISSUE TITLE
Displaying mensural MEI in multiple lines

### ISSUE THREAD

**Issue by misingnoglic** [rism-ch/verovio#530]
Hello,
Thank you everyone for your previous help. I've successfully been able to convert mensural MEI files into SVG files - I've made a simple flask app to do just that: https://github.com/misingnoglic/measuring_polyphony

From my previous issue, I've learned that I have to set tk.setNoLayout(True) for it to work. However, the MEI is created as one giant line, which makes it hard to place it in a website. Is there any setting I can toggle to make it not just appear in one giant line? Here is an example of what it renders like right now:

http://www.cs.brandeis.edu//~arya/adesto_MENSURAL.mei.html

I tried changing the page size, but I assume setNoLayout makes those options irrelevant. 
Thank you!

**Comment by ahankinson** [comment]
Have you worked your way through the Verovio tutorial?

http://www.verovio.org/tutorial.xhtml?id=topic

You can download the zip file and work through the examples, which should give you some things to play with and figure out the options for working with the JavaScript toolkit.

**Comment by lpugin** [comment]
This is currently not possible. Casting off mensural notation is not straightforward because the system breaks are not given and need to be determined. With your case, one option would be to have system breaks allowed at all positions where there is a barLine at all voices at the same time. This could be fairly straight forward to implement assuming 1) always one single layer per staff, 2) always the same number of staves throughout the the piece, and 3) no editorial markup is used above layer elements. If this is a way to go I can help you to implement it. Is it something you could do?

However, this would work only if barLine elements are provided. If not we can look at positions where all voices (staff/layer) have an note onset. The problem here is that this would not necessary align with a metric alignment (e.g., a breve) even though it is quite likely to do so depending on the music. More refined casting off would require to take into account the metric positions but would could leave this for a later point.

**Comment by karend27** [comment]
Hi Laurent,
Arya (misingnoglic) is a student working with me to get my MEI mensural pieces up on the web using Verovio (he's a computer science/music double major and has Python and other programming skills). The first option sounds best to me - 1 and 2 are always true in the pieces we have so far.
With respect to 3, at the moment we don’t have any editorial markup at all, possibly we might eventually have some but I don't think it would be a problem to keep that within the layer elements. So I think that in general, there is no problem with these conditions. So if you were able to allow system breaks where barLine lines up in all voices that would be great. Best, Karen

**Comment by donbyrd** [comment]
To clarify things (I hope), @lpugin points out that "casting off mensural notation is not straightforward because the system breaks are not given and need to be determined", but it sounds like @karend27 would be happy if she and her student could tell Verovio where system breaks should be. I don't think that's is possible now, or is it?

**Comment by lpugin** [comment]
@donbyrd as I said, this is indeed currently not possible.

**Comment by donbyrd** [comment]
OK. I thought you might just have meant it wasn't possible for Verovio to decide line breaks automatically. Thanks for the clarification.

**Comment by pe-ro** [comment]
I'm confused about this too.  Do you mean it's not possible to indicate system breaks for mensural notation in the markup?

**Comment by lpugin** [comment]
You can but it is currently ignored by Verovio ;-) As I said above a proposal is to use barLine elements as possible system break positions when automatic layout is used. That is, if the width of the window (or page) is not wide enough to fit all the music, then Verovio can look at barLine element to see where to cut.

Now this is of course different from `<sb/>` that indicate how the page has be cast off in a fix  way (e.g., in a non responsive manner).

**Comment by pe-ro** [comment]
Doesn't using `<sb>` to mark a non-responsive/non-dynamic break point contradict how it's used by Verovio for CMN?

**Comment by lpugin** [comment]
No, this is how they are used too. You can either have Verovio produce a
fixed layout as given by sb or let it ignore them and determine its own one
for responsive rendering.

**Comment by pe-ro** [comment]
Thanks for the clarification.

**Comment by donbyrd** [comment]
I'm sorry, but I'm confused again, Laurent! You seem to be saying, for mensural notation, that (1) specifying the layout yourself via `<sb>` doesn't currently work, and (2) that having Verovio decide the layout itself would be quite difficult. But I think many folks interested in mensural notation, including Giuliano and others here at IU (though I haven't asked), would be satisfied  with specifying the layout via sb. And it doesn't seem to me that it could be very difficult to make that work. Am I missing something?

**Comment by lpugin** [comment]
You are not missing anything. However, making it work by taking into account given `<sb/>` or by looking at `<barLine/>` (as potential system breaks) would be equally difficult. 

For mensural notation, Verovio creates a container (basically the equivalent of a measure) that contain the staves. This can only be displayed as one system. In order to have system break, we need to have (at least) one of these per system. Splitting the container by looking at `<sb/>` or by looking at `<barlLine/>` is similar, so once we have one working we will actually already have the other. Does it make sense?

**Comment by donbyrd** [comment]
Yes, I get it now! Though I think you really mean that once we have the capability of splitting the container at all, having Verovio decide where to do it (instead of just using `<sb/>`s) will be straightforward, and much easier than the container splitting. Right?

**Comment by lpugin** [comment]
Yes, this is it.

**Comment by lpugin** [comment]
Implemented here f67abbc92b69243af66f7bcc509e8051a3a169b2

System break occur only where there is a `<barLine>` on all staves / layers/. There is also an experimental option (--mesural-to-measure) that converts the MEI from mensural sections to measures, with the same requirement.
