### ISSUE TITLE
slur disappears at system break

### ISSUE THREAD

**Issue by juyaolongpaul** [rism-ch/verovio#619]
Hi Verovio team,

I just found out a small problem with the viewer:

![screen shot 2017-06-12 at 10 51 15 am](https://user-images.githubusercontent.com/9313094/27039806-13ca600e-4f5d-11e7-9e13-684dc255d344.png)

At the end of the third line and the beginning of the fourth line, there is an incomplete slur, which should connect the note from the end of the third line (note A) with the very first two notes of the fourth line (note G F). However, there is no partial slur on note A in this zoom. When I adjust the zoom, it will show properly if these three notes are not on end edge of different lines:

![screen shot 2017-06-12 at 10 54 01 am](https://user-images.githubusercontent.com/9313094/27039926-77d91d42-4f5d-11e7-9b4a-d7ffc801ed29.png)

(These three notes can be found in the middle of the second line, right before the word 'ri-', there is a complete slur over these three notes, which should also be the case in the first screenshot)

Could you fix this?

Thank you!

**Comment by craigsapp** [comment]
Firstly, you should attach the data file with the problem into the issue; otherwise, it cannot be fixed (or will be fixed much more slowly than if the test file were included).

There are two possible ways to attach a file:

(1) drag and drop the file into the text message.  There will probably be problems with using the extension `.mei` or `.xml`, so you may have to rename it to end in `.txt`.

(2) If the file is less than about 4000 lines, you can embed the text of the file within the message directly.  To do this add three back quotes followed by the string "xml", then the contents, and end the contents with three back quotes:

```
    ```xml
    <?xml?>
    <root-node>
    </root-node>
    ```
```

This will display on the page is:

```xml
<?xml?>
<root-node>
</root-node>
```

**Comment by juyaolongpaul** [comment]
The file is here:

[Inter_aulicos_proceres_primi_tuo_cinii_tempus_ingressus.mei.txt](https://github.com/rism-ch/verovio/files/1071730/Inter_aulicos_proceres_primi_tuo_cinii_tempus_ingressus.mei.txt)

Thank you for your help!

Yaolong

**Comment by lpugin** [comment]
The slurs should always be in the measure where they start. This is not the case in your data.
