### ISSUE TITLE
n on scoreDef

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#659]
In the develop branch the `@n` on `scoreDef` is no longer available. Is this done on purpose?

**Comment by lpugin** [comment]
No particular reason. (It used to be available through AttCommon, I think)

**Comment by rettinghaus** [comment]
I thought to use it for *movement designation* as long we can't easily access `<mdiv>`. Would it make (more) sense to have `@n`, `@label`, and `@type` available on `<score>`?

**Comment by lpugin** [comment]
@rettinghaus what would you like to do with this?

**Comment by rettinghaus** [comment]
In an ABC collection every piece has a "reference number". When importing I want to put this somewhere (like a "movement designation"). As `scoreDef` is easily accessible, I put it there. But it seems to make more sense (to me) to put it on `mdiv` or `score`. `mdiv` is not available, so this leaves `score`.

**Comment by lpugin** [comment]
Wouldn't it make sense to put it in the header?

**Comment by pe-ro** [comment]
If you're talking about the MEI development branch, `@n` is still available on `<mdiv>`, `<score>`, and `<scoreDef>`.  `@n` is intended to hold a sequential number for a collection of the same or similar elements, for example --
```
<mdiv n="1"/>, <mdiv n="2"/>, <mdiv n="3"/>, ...
```
However, if ABC's "reference number" is more like an identifier than a sequence number, then it shouldn't be placed in `@n`, `@label`, or `@type`.  It could go in `@xml:id`, if it fits the convention for XML ids.  If none of those locations fit the bill, then it's metadata, and therefore belongs in the header as a descriptor of the source material.

**Comment by lpugin** [comment]
@pe-ro where in the header would be the most appropriate place?

**Comment by pe-ro** [comment]
It depends on the function of the "reference number". `<identifier>` is the most logical target, I think.  But its precise location depends on whether it functions as an identifier of the work, a particular manifestation/source, or something else.

**Comment by lpugin** [comment]
I will leave you guess ;-)
http://abcnotation.com/wiki/abc:standard:v2.1#xreference_number

**Comment by rettinghaus** [comment]
As you can see there, the reference number is indeed a positive integer. 
ABC can store multiple pieces/movements in one file: 

```
X:1
% some music
X:2
% some other music
X:12
% even more music
```

which simply would be converted to MEI

```
<mdiv n="1"/>
<!-- some music -->
<mdiv n="2"/>
<!-- some other music -->
<mdiv n="12"/>
<!-- even more music -->
```

@pe-ro question is, where should it be put instead, as it is not possible to set `@n` on `<mdiv>` in Verovio. But it could be added to `<score>` or `<scoreDef>`.

**Comment by lpugin** [comment]
Verovio would not be able to output multiple `<mdiv>`, wouldn't it? So you will have one MEI file per ABC movement, in which case you can still put it in the header.

**Comment by rettinghaus** [comment]
I *could*. But I don't want to. Most of the tune header is not really metadata but goes into `<scoreDef>`. 

Also you could batch process a whole file and merge all resulting MEIs, and in that case you would at least need a `xml:id` on mdiv to reference the `<identifier>` in the header.

**Comment by pe-ro** [comment]
Since ABC's reference number is indeed an integer denoting position in a sequence of "tunes", I think it should be written to `mdiv/@n`.  This should be possible regardless of the fact that Verovio can only currently output a single `<mdiv>`.  If Verovio doesn't allow writing more than one `<mdiv>` per file, or more precisely, doesn't allow distinguishing different `<mdiv>` elements via `@n`, then the result of the conversion has to be multiple files.  Pushing the reference number to the header to accommodate Verovio isn't justifiable.

Is there a possibility that at some point there might be a command-line option in Verovio to select a particular `<mdiv>` to be rendered based on `@n` or other criteria?  Provision of this option would be a win-win -- Verovio can be used without limitation for ABC conversion to MEI and it can still render one `<mdiv>` at a time.

**Comment by pe-ro** [comment]
@lpugin : Why can't / shouldn't Verovio output more than one `<mdiv>`?

It would be stretching the definition of `@n` considerably, but even if Verovio  continues to output only one `<mdiv>`, then `@n` should still be used for the ABC ref number.  I still wouldn't move ABC's number to the header because, as @rettinghaus points out, doing that would complicate any later merging process.

**Comment by lpugin** [comment]
@lpugin <https://github.com/lpugin> : Why can't / shouldn't Verovio output
more than one <mdiv>?


Basically the assumption is different mdivs are likely to have different
score definitions (for example for different movements with different
instruments). For this reason, only one mdiv can be rendered at a time.
However, selecting what mdiv to render is already possible.

It would be stretching the definition of @n considerably, but even if
Verovio continues to output only one <mdiv>, then @n should still be used
for the ABC ref number. I still wouldn't move ABC's number to the header
because, as @rettinghaus <https://github.com/rettinghaus> points out, doing
that would complicate any later merging process.

There is no reason for not having the ABC is in mdiv@n. It just needs to be
implemented.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rism-ch/verovio/issues/659#issuecomment-328175721>, or mute
the thread

**Comment by pe-ro** [comment]
> selecting what mdiv to render is already possible

> There is no reason for not having the ABC ~~is~~ in mdiv@n. It just needs to be implemented.

Perfect!

**Comment by pe-ro** [comment]
> Basically the assumption is different mdivs are likely to have different score definitions (for example for different movements with different instruments). For this reason, only one mdiv can be rendered at a time.

But, changes in score definition are already allowed within an `<mdiv>`, say from one `<section>` to another.  If that's true, then it's not outside the realm of possibility to allow changes in score definition from one `<mdiv>` to the next, right?

**Comment by pe-ro** [comment]
But, I do see how it could be difficult to deliver a gigantic SVG file containing all `<mdiv>`s. In addition to any layout problems caused by changing performing forces from movement to movement, it could take a long time to produce one big file.  On the other hand, if a batch of SVG files were returned, I'm not sure how one could navigate from one to the other.

If only there were an existing format for presenting a mixture of text and images in a web browser!  😉 Could Verovio produce an HTML file containing multiple SVG graphics when there was more than one `<mdiv>`?  This could be the foundation for some really cool applications.  In spite of the time it might take to create, an "MEI book" (as HTML with embedded SVG) would be a wonderful thing!

(Aside: Perhaps this puts a whole new light on our stylesheet language discussions.)

**Comment by pe-ro** [comment]
In case you haven't noticed yet, https://github.com/music-encoding/music-encoding/issues/457 proposes allowing one to mix `<div>` (for text) and `<mdiv>` (for music) within the MEI `<body>`.  I think you can already see where this is going.

My thinking is that, since this mixture is already allowed in plenty of other places in MEI, it should be available within `<body>`.  This doesn't mean that Verovio has to support anything above `<mdiv>`, but it would be nice if it started moving in that direction. 😄

**Comment by kepper** [comment]
I’m not so sure if Verovio should really start to render multiple mdivs. It seems reasonable for me to use a parameter to decide which mdiv to render, but leave the actual treatment of multiple movements to an application that utilizes Verovio. After all, Verovio is a library. Implementing something like a "default MEI book“ as HTML with multiple embedded SVGs goes into a significantly different direction, and I don’t think that this would be wise for Verovio. However, the stylesheets you’ve mentioned could be a much better place for something like this. It requires a webservice running Verovio, but that shouldn’t be too much of a problem, I guess ;-)

**Comment by pe-ro** [comment]
Another piece of software or a webservice running Verovio is fine too.

**Comment by lpugin** [comment]
@rettinghaus could you provide us with some (links to) abs files that have multiple pieces?

**Comment by rettinghaus** [comment]
Here is plenty:
http://ifdo.ca/~seymour/runabc/esac/esacdatabase.html
http://www.village-music-project.org.uk/?page_id=52

**Comment by craigsapp** [comment]
Here is another website with ABC files: https://thesession.org

Example page: https://thesession.org/tunes/829#setting31004

Clicking on the "Download ABC" button on the page:

<img width="228" alt="screen shot 2017-09-11 at 2 56 55 am" src="https://user-images.githubusercontent.com/3487289/30269205-f29640f6-969c-11e7-9d2b-c97a10d95b07.png">

will download a tunebook ABC files containing all of the tunes on the page.

**Comment by lpugin** [comment]
OK, I see. If you want to have convert them with each piece in a separate MEI file with `@n` on `mdiv` then we can add a member to Doc for storing what we need.

Making Verovio convert all of them in one MEI file with several `mDiv`s would require quite some developments.

Alternatively, you can make each "piece" a section. (Having section within section is supported by Verovio.)

**Comment by craigsapp** [comment]
How would the function of the `<section>` be indicated? (such as "work" in this case, or "movement" in others, or even "act")

**Comment by lpugin** [comment]
Something like
```xml
<section n="1" label="Hag At The Churn">
  ...
</section>
<section n="2" label="Hag at The Churn">
  ...
```
?

**Comment by craigsapp** [comment]
You are storing the title of the work in the label attribute, but there is no indication that the content of `<section>` is a "work".

perhaps: 

```
<section n="1" label="work">
  ...
</section>
<section n="2" label="work">
  ...
```

Or in other words, is there a formalized system in MEI for indicating the content organization of the file, such as "this MEI file contains a collection of single-movement works" as in this case, or "this section encodes a [single-movement] work"?

**Comment by rettinghaus** [comment]
Sections cannot contain seperate works. Every piece has a score of it's own, and `<section>` is alway contained in `<score>`. 

One could argue, that all tunes in one file represent basically one "musical division". But they're definitely different scores.

**Comment by pe-ro** [comment]
There are two approaches that might be helpful here --

1. `<group>` allows the gathering of multiple `<music>` elements.  For example --
```
<mei xmlns="http://www.music-encoding.org/ns/mei">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt/>
    </fileDesc>
  </meiHead>
  <music>
    <group>
      <!-- Each "tune" gets its own music element -->
      <music label="Tune 1>
        <body>
          <mdiv"/>
        </body>
      </music>
      <music label="Tune 2">
        <body>
          <mdiv/>
        </body>
      </music>
     <!-- ... -->
    </group>
  </music>
</mei>
```
This would allow Verovio to maintain its conceit that `<body>` can only contain a single `<mdiv>`.  However, `<group>` does not accommodate independent metadata for each separate `<music>` element.  If `<group>` is used, then all the metadata must go in a single `<meiHead>`, where it can be referred to using `@decls`.

2. `<meiCorpus>` facilitates the gathering of multiple MEI files.  For example --
```
<meiCorpus xmlns="http://www.music-encoding.org/ns/mei">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt/>
    </fileDesc>
  </meiHead>
  <!-- Each tune gets its own "mei" file -->
  <mei>
    <meiHead>
      <fileDesc>
        <titleStmt>
          <title/>
        </titleStmt>
        <pubStmt/>
      </fileDesc>
    </meiHead>
    <music label="Tune 1">
      <body>
        <mdiv/>
      </body>
    </music>
  </mei>
  <mei>
    <meiHead>
      <fileDesc>
        <titleStmt>
          <title/>
        </titleStmt>
        <pubStmt/>
      </fileDesc>
    </meiHead>
    <music label="Tune 2">
      <body>
        <mdiv/>
      </body>
    </music>
  </mei>
<!-- ... -->
</meiCorpus>
```
In this example, `<body>` still contains a single `<mdiv>`, but now each `<music>` element is contained by an `mei` ancestor, which of course can have its own metadata header.

How one deals with the metadata is the deciding factor between these possibilities.

**Comment by pe-ro** [comment]
> is there a formalized system in MEI for indicating the content organization of the file, such as "this MEI file contains a collection of single-movement works" as in this case, or "this section encodes a [single-movement] work"?

A collection of works (with single or multiple movements) can be represented using either a `<corpus>` or a `<group>` element, depending on how one handles the metadata.  A single work (with one or more movements) is represented by a file containing one `<music>` element.

**Comment by lpugin** [comment]
Since we have cases where each piece has its own metadata (see http://www.village-music-project.org.uk/?page_id=807) it seems that `<meiCorpus>` would be an interesting direction, wouldn't it?

**Comment by pe-ro** [comment]
Yes, I think `<meiCorpus>` is a better place to start than `<group>`.

**Comment by lpugin** [comment]
Somehow duplicates with #707
