### ISSUE TITLE
compile error on centos

### ISSUE THREAD

**Issue by csy7070** [rism-ch/verovio#671]
cmake . -DMUSICXML_DEFAULT_HUMDRUM=ON
make

.........

/usr/local/verovio/src/hum/humlib.cpp: In member function ?.ool hum::HumRegex::getGlobal()?.
/usr/local/verovio/src/hum/humlib.cpp:4748:9: error: no match for ?.perator!?.(operand type is ?.td::bitset<11ul>?.
  return !(m_searchflags & std::regex_constants::format_first_only);

centos6.5  
cmake version 2.8.12.2 
gcc (GCC) 4.8.2

Can somebody help me?

**Comment by craigsapp** [comment]
The problem is that you cannot use gcc version 4.8.2 with C++11 regular expressions, which is what is happening here.  GCC Version 4.9 or higher is required.

Try

```bash
cmake . -DNO_HUMDRUM_SUPPORT=ON
```
To compile without Humdrum support.

You might also have to disable PAE support:

```bash
cmake . -DNO_HUMDRUM_SUPPORT=ON -DNO_PAE_SUPPORT=ON
```

If you are needing Humdrum support, then you will have to use GCC 4.9 or higher.   But installing GCC updates not coordinated with your OS version can be messy.  A link related to Centos 6.5:
https://superuser.com/questions/834862/how-to-install-g-4-9-2-in-cent-os-6-5

**Comment by csy7070** [comment]
thank you
