### ISSUE TITLE
adjusting page height is modifying resulting SVG width

### ISSUE THREAD

**Issue by MaximeTuab** [rism-ch/verovio#733]
Hi, I'm working with the c++ API, master branch.
First, thanks for this impressive work!
I see that when setting adjustPageHeight to True, the width of the resulting SVG is modified, but I don't understand why, and how the width is modify.
Thank you for your help!
M.

**Comment by craigsapp** [comment]
When set to true, `adjustPageHeight` will shrink the vertical height of the SVG to match the vertical bounding box of the notation on the page rather than the page height.  This removes white space from the SVG below the notation in an under-filled page of music.

There is no equivalent for the width.  This would not be necessary for music longer than one system break.  It might be nice for music shorter than one system that takes up less than the width of the page.

**Comment by MaximeTuab** [comment]
Thank you for the quick answer. I understand that this option adjust page height without modifying width, and I agree this is the expected behavior.
Unfortunately, in my case, width is also modified, but I don't know why...

**Comment by craigsapp** [comment]
Also, you might want to use the `develop` branch which contains the most recent version of the code (more features with added/fixed bugs).  To do this from git:

```bash
git checkout develop
git pull
```

**Comment by craigsapp** [comment]
Can you give an example where width is affected?  Do you mean that every line of music has a different width?  And what happens if you remove the `<pb/>` and <sb/>` elements from the music before printing in verovio?

**Comment by craigsapp** [comment]
Somewhat related to issue https://github.com/rism-ch/verovio/issues/714

**Comment by MaximeTuab** [comment]
After some tests, I see that the problem does not from Verovio, but from the code calling the library (integration in a iOS WKWebView that does not manage as well as expected its content size...). Thank you again for your help and for this huge job!
