### ISSUE TITLE
Render <label> and <labelAbbr> inside <verse>

### ISSUE THREAD

**Issue by peteranglea** [rism-ch/verovio#913]
Since the MEI schema was recently updated to allow for <label> and <labelAbbr> elements inside <verse>, can Verovio be updated to allow rendering of this? This is a great addition and will be very helpful for music with stanza numbers, etc.

See music-encoding issue #514: https://github.com/music-encoding/music-encoding/issues/514

**Comment by lpugin** [comment]
There are some peculiarities for the implementation of this feature
* The element `<labelAbbr>` is not rendered directly where it is (should it be better encoded in `<staffDef>`? Or in new `<verseDef>`?)
* The `<labelAbbr>` element is not a `LayerElement` class nor a `TextElement` within `LayerElement`

![image](https://user-images.githubusercontent.com/689412/82983216-039fe780-9ff0-11ea-96b9-03ff5c98a4fa.png)

# Implementation steps

## Step 1 bdaf1402b2b5252b237cfbba5cdc8fab382eeb0c

**Allow `Label` and `LabelAbbr` into `Verse`**

Modify `Verse::AddChild()`

## Step 2 8121c1c87d7e212ff3ec2a62c88e82db03aaa60f

**Read / Write `Label` and `LabelAbbr` from / to `Verse`**

Modify `Input::ReadLayerChildren()`

Modify `Input::IsAllowed()` and change the filter for `VERSE` parent (line 2647)

## Step 3 31bdb5292856417a93b200e3603f2d15e0c7c661

**Avoid `View::DrawLayerChildren` to crash (line 1400)**

Because we now have non `LayerElement` objects in the tree, we should not `assert(false)` when the object is a `Label` or a `LabelAbbr`.

## Step 4 97b410f2de0b2276506199171957e5240ce38238

**Add a pointer to the `LabelAbbr` when it will be expected to be displayed**

Add a public `LabelAbbr *m_drawingLabelAbbr` to `Verse` that will point to the `LabelAbbr` in the tree at the beginning of a system. Set the pointer to `NULL` in `Verse::Reset()`

Add a `virtual int ResetDrawing(FunctorParams *functorParams)` Functor to `Verse` for resetting the pointer to `NULL`. Don't forget to call the parent functor!

## Step 5 153f469b32666d1f6b9ba32e9455d92122a720b4

**Make the pointer point to the 'LabelAbbr'**

For this, we are going to use an existing Functor that process the data verse by verse. It is `Object::AdjustSylSpacing`.

First we need to add a member `LabelAbbr *m_currentLabelAbbr;` to the Functor parameter object `AdjustSylSpacingParams` that will hold the reference to the current abbreviation. Initialize it to `NULL`.

Modify `Verse::AdjustSylSpacing` (line 128):
1. if there is a `Label` descandant, reset the current abbreviation (in the Functor parameter object) to `NULL`.
2. set `m_drawingLabelAbbr` to `NULL` (even if it should always already be the case)
3. set the Functor parameter object `m_currentLabelAbbr` to the child `LabelAbbr` descendant (if any). 

Modify `Verse::AdjustSylSpacing` (line 172): we are at the beginning of a system, so if the abbreviation is not new it this verse and there is one, make the `m_drawingLabelAbbr` point to it.

## Step 6 a3e653a0730f9a577229aab11588dabbf0b424d5

**Draw the label or the abbrevitation**

Modify `View::DrawVerse`
1. check if there is a descendant `Label` or if the `m_drawingLabelAbbr` is set
2. if yes, get the label as `std::wstring labelStr` with `GetText()`
3. set the `FontInfo`:
```cpp
FontInfo labelTxt;
if (!dc->UseGlobalStyling()) {
    labelTxt.SetFaceName("Times");
}
labelTxt.SetPointSize(m_doc->GetDrawingLyricFont(staff->m_drawingStaffSize)->GetPointSize())
```
4. set the `TextDrawingParams`:
```cpp
TextDrawingParams params;
params.m_x = verse->GetDrawingX() - m_doc->GetDrawingUnit(staff->m_drawingStaffSize);
params.m_y = staff->GetDrawingY() + this->GetSylYRel(std::max(1, verse->GetN()), staff);
params.m_pointSize = labelTxt.GetPointSize();
```
5. draw it

# Keep in mind that

* Not drawing the `LabelAbbr` in place is unusual.

* Drawing the `Label` descendant from within `Draw::Verse` is not the normal way to proceed. Normally, children will be drawn recursively through a call to `View::DrawLayerChildren()`.

* This implementation does not do any spacing adjustment for the labels and it can overlap with other elements.

**Comment by craigsapp** [comment]
`<verseDef>` is an interesting possibility.  It could store default font/font sizes for the verses as well as vertical spacings between verses, etc.
