### ISSUE TITLE
key signature, phrasing slurs, and crescendo hairpins render incorrectly with node package

### ISSUE THREAD

**Issue by jefftrevino** [rism-ch/verovio#921]
The Verovio node package does not render a key signature or phrasing slurs, and incorrectly renders crescendo hairpins, when [this sample Chopin encoding](https://raw.githubusercontent.com/music-encoding/sample-encodings/master/MEI_3.0/Music/Complete_examples/Chopin_Etude_op.10_no.9.mei) opens in Verovio via the mei-tools-atom package. (Tested versions 2.0.0-4 through 2.0.0-39.)

**Comment by craigsapp** [comment]
More description of the problem would be useful, such as how they are incorrectly rendered.  A screenshot would be good.  This can be done by dragging an image file into the text-box of an issue when it is in "Write" mode.

Here is what it looks like in the emscripten-compiled version (but not the node version):

<img width="1738" alt="screen shot 2018-07-23 at 7 06 28 am" src="https://user-images.githubusercontent.com/3487289/43058247-f021d32e-8e46-11e8-8a59-d4ac0c8f68a7.png">

This probably looks the same (no key signature, where there should be four flats).

The key signature is encoded as:

```
          <scoreDef meter.count="6" meter.unit="8" key.pname="f" key.mode="minor" midi.bpm="144">
```

Perhaps not recognized by verovio, but this method should be:

```
          <scoreDef meter.count="6" meter.unit="8" key.sig="4f" midi.bpm="144">
```

The first phrase slur in measures 2-4 is missing (I haven't checked to see if it is in the data).

**Comment by lpugin** [comment]
@craigsapp is right for the encoding of the key signature. I do not understand what is this issue with slur and hairpin. Please clarify it.

**Comment by craigsapp** [comment]
Also related to the missing key signature is that `@key.pname` and `key.mode` are viewed as "analytic information" and therefore not  rendering in the graphical notation.  For example, music could be in F minor, but the key signature could be something other than four flats (such as a region of music in F minor when the main key is C minor).  Here is some discussion related to that:
    https://github.com/music-encoding/music-encoding/issues/525

Also this particular file originates from a Humdrum file that was then converted to MusicXML and then MEI.  Then the MEI was converted several times to the most recent version of MEI.  The original Humdrum encoding can be viewed here:

http://verovio.humdrum.org/?file=chopin/etudes/etude10-09.krn

<img width="1278" alt="screen shot 2018-07-23 at 5 33 39 pm" src="https://user-images.githubusercontent.com/3487289/43086768-71177400-8e9e-11e8-91c0-785bca9e75ab.png">


You can then press `alt-m` to view the MEI conversion done by verovio inside the webpage:

<img width="1634" alt="screen shot 2018-07-23 at 5 34 28 pm" src="https://user-images.githubusercontent.com/3487289/43086797-842942ee-8e9e-11e8-9a50-b73417406336.png">

You can also press `alt-p` to view a PDF of the source edition used to encode the Humdrum file. 

<img width="932" alt="screen shot 2018-07-23 at 5 35 58 pm" src="https://user-images.githubusercontent.com/3487289/43086881-ba27511a-8e9e-11e8-98e0-dda32314f4a6.png">


 There will be some limitations in the rendering, but for the most part the rendering of the Humdrum data/MEI conversion should match the source edition PDF, so it would be better to use this file for bug reports than the one you used, since this one is designed for use in verovio.
