### ISSUE TITLE
Issue of Highlighting

### ISSUE THREAD

**Issue by hondaaaaaaaaaa** [rism-ch/verovio#950]
I tried the tutorial of "Highlighting content"(https://www.verovio.org/tutorial.xhtml?id=topic03) but each first measures from 2nd staffs didn't turn blue.
![default](https://user-images.githubusercontent.com/28131539/48044244-4e6bcb80-e1ce-11e8-869d-b76d8f143b7e.PNG)

If this issue already was solved please tell me the solution.

**Comment by lpugin** [comment]
This is the consequence of having measure numbers in a element https://github.com/rism-ch/verovio/issues/558

The CSS selector needs to be adapted. I leave this to CSS experts. If somebody has the solution please make a PR.

**Comment by musicEnfanthen** [comment]
This is an issue pretty hard to debug because the CSS (`".staff:nth-child(2)"`) used to work fine  **only by accident**.

According to this: https://stackoverflow.com/a/5546296, the selector `.className:nth-child(2)` does not really select the second child with `className` but the second child of the element type. So it will match always the second `g` element in this case as there are only `g` elements inside `.measure` instead of mathing the second `g` element with class name `staff`. Changing the selector to `nth-of-type()` has the same effect. Using these selectors, you can only match the nth child of a given **element**.

Apparently, there seems to be no similar CSS Selector to match e.g. the second (or nth) child of a given class.

Will provide a PR that makes use of the solution mentioned here: https://stackoverflow.com/a/6447072 . It selects all siblings of the nth child, applies the attributes to all of them and then removes them from all n+1 siblings.
